### ISSUE TITLE
From heatmap view, when I save proteins to group, the dialog box doesn't go away

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#79] opened 2015-03-20 16:05 UTC
I successfully created the group, but the box remains
![screen shot 2015-03-20 at 12 03 40 pm](https://cloud.githubusercontent.com/assets/11475316/6755412/4de221dc-cef9-11e4-9f17-91eac83a2a84.png)

**Comment by hyoo** [comment] 2015-03-23 16:17
I cannot reproduce this issue. When you click "Add Proteins To Group", that dialog should be closed and Workspace one should show up.

**Comment by mshukla1** [comment] 2015-06-11 03:23
Can't reproduce, seems to be fixed now.

**Closed by mshukla1** 2015-06-11 03:23 UTC
