### ISSUE TITLE
Refresh on job page scrolls view away

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#548] opened 2015-11-24 22:38 UTC
If you're looking down the page on the job page and it refreshes it scrolls back up to the top so you have to move the page back to where you were looking before.

**Comment by olsonanl** [comment] 2015-11-25 15:04
I want to add that with a lot of jobs this becomes really annoying - at this point I can't tell what the status is of jobs I'm trying to check since by the time I find them the page scrolls back to the top .

**Comment by mshukla1** [comment] 2015-11-25 16:57
I agree. It always frustrates me!

**Comment by dmachi** [comment] 2016-12-01 16:03
Duplicate of another ticket, but this is fixed.

**Closed by dmachi** 2016-12-01 16:03 UTC
