### ISSUE TITLE
Job display scrolls out from under you

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1724] opened 2017-09-20 19:23 UTC
When the jobs page updates and you are scrolled down trying to find something it zips back to the top. This problem is compounded if you have a sort in place on one of the columns.

**Comment by nconrad** [comment] 2017-09-20 19:55
#websockets

**Comment by nconrad** [comment] 2017-09-20 19:57
another option:  we could just put a refresh button, since we may be trying to hard?

**Comment by olsonanl** [comment] 2017-09-20 20:20
websocket is an orthogonal issue since if the page rerenders on a websocket update you still have the scroll-while-reading problem.

If you are going to do any async updates they need to leave the page in the same location with the same sort order selected. Perhaps don’t touch the page if the user has been manipulating it at all.

—bob

On Sep 20, 2017, at 2:57 PM, nconrad <notifications@github.com<mailto:notifications@github.com>> wrote:


another option: we could just put a refresh button, since we may be trying to hard?

**Comment by mshukla1** [comment] 2017-12-12 12:02
I believe the issue is addressed with the recent changes to the jobs page. Closing the ticket.

**Closed as completed by mshukla1** 2017-12-12 12:02 UTC
Labels: Fixed, UI: Jobs
