### ISSUE TITLE
Clustering on heat map never worked

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1043] opened 2016-10-10 20:21 UTC
Just a circle spinning...no results.  Anchoring did work, btw.
<img width="1425" alt="screen shot 2016-10-10 at 4 20 10 pm" src="https://cloud.githubusercontent.com/assets/11475316/19249871/9cabc46c-8f05-11e6-98d5-b843202e0d70.png">

**Comment by hyoo** [comment] 2016-10-11 12:07
#673

**Comment by dmachi** [comment] 2016-10-11 19:59
Closed as duplicate of #673

**Closed as completed by dmachi** 2016-10-11 19:59 UTC
