### ISSUE TITLE
How many items are in a workspace directory?

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1839] opened 2018-01-02 13:40 UTC
![image](https://user-images.githubusercontent.com/7661533/34485432-48098d62-ef90-11e7-8b72-bbf990c16ad7.png)

**Comment by mshukla1** [comment] 2018-01-02 13:46
Hi Jim, 

Can you elaborate your question? Are you asking what is the max number of items allowed 
in a workspace directory? 

-Maulik

**Comment by nconrad** [comment] 2018-01-02 17:47
I'm guessing this is duplicate of https://github.com/PATRIC3/patric3_website/issues/1625 .  We could either add a count under the folder path/breadcrumbs at the top, or we could add a new bar at the bottom, making the design somewhat similar to other grids.  This may be considered a waste of space though, since pagination is not being used.   I.e.: 

![image](https://user-images.githubusercontent.com/1194246/34493610-579adb9c-efb2-11e7-99a5-45bea76ef7f5.png)

I think I'd prefer a small "4016 items" under the folder path.

**Comment by rkenyon** [comment] 2018-08-03 20:14
Jim triage comment: Medium.  I have several workspace directories with thousands of jobs.  p3-ls is the only way to count the number in a given directory.   Every other table on the website has a count at the bottom.  I don't know why this one stalled out. I'd be happy to have a count in the side bar as an alternative. Regardless, I find myself in need of this all the time.

**Comment by nconrad** [comment] 2019-08-15 23:17
The count was added to the breadcrumbs awhile back.  closing.

**Closed as completed by nconrad** 2019-08-15 23:17 UTC
Labels: Enhancement, UI: Workspace
