### ISSUE TITLE
Annotation service keeps inserting its own name

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#327] opened 2015-07-02 20:35 UTC
Very annoying.  I am trying to annotate a new genome that hasn't been published.  The strain is 8471, and which I enter (see screenshot) and a mysterious autofill pops up:
![screen shot 2015-07-02 at 4 29 19 pm](https://cloud.githubusercontent.com/assets/11475316/8487187/389138c8-20d8-11e5-87ee-321931610fa4.png)
Then, when I try and submit it, it keeps giving that horrible autofill and I can't get rid of it:
![screen shot 2015-07-02 at 4 29 35 pm](https://cloud.githubusercontent.com/assets/11475316/8487193/48a34fd0-20d8-11e5-9c30-3a33a4ce679e.png)

I am finding this to be extremely frustrating.

**Comment by olsonanl** [comment] 2015-08-04 19:31
I think Andrew has a proposed new interface for this; maybe put it in place on beta and have folks give it a try?

**Comment by olsonanl** [comment] 2015-08-04 19:40
closed as a duplicate of #307

**Closed** 2015-08-05 20:16 UTC
Labels: Services
