### ISSUE TITLE
Clustering on heat map returned time out error

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1052] opened 2016-10-10 20:30 UTC
<img width="1401" alt="screen shot 2016-10-10 at 4 29 59 pm" src="https://cloud.githubusercontent.com/assets/11475316/19250146/da900c10-8f06-11e6-9e47-0a9750f51214.png">

**Comment by hyoo** [comment] 2016-10-11 12:06
#673

**Comment by dmachi** [comment] 2016-10-11 19:48
Closed as duplicate of #673

**Closed as completed by dmachi** 2016-10-11 19:48 UTC
