### ISSUE TITLE
backbutton + keyword search breaks filters on features tab

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#873] opened 2016-08-19 18:36 UTC
1. go to features tab and provide keyword to search
2. add filter (PATRIC & CDS) 
3. click to go to feature page
4. back button
5. have refseq features!

<img width="1272" alt="features" src="https://cloud.githubusercontent.com/assets/1236467/17820250/7aa216c2-6611-11e6-9f19-f118f0278254.png">

**Comment by dmachi** [comment] 2016-08-31 03:41
I can't reproduce this following this particular list, but I know there are some bugs in the filtering selection.  I'm tracking those fixes on #884.  Closing this as a duplicate more or less.

**Closed by dmachi** 2016-08-31 03:41 UTC
