### ISSUE TITLE
genome groups in tree service

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1614] opened 2017-07-25 19:53 UTC
In the tree service submission app the genome groups dropdown doesn't work properly (doesn't auto fill genome group names, and I need to know where to go in the hierarchy to find my genome groups).

When I do find a genome group, clicking the + button doesn't do anything.

**Comment by dawenx** [comment] 2017-07-25 20:23
Are you reporting issue for below link?
https://www.alpha.patricbrc.org/app/PhylogeneticTree

This particular part works for my local copy which is written before the new workspace.

@nconrad @hyoo @zreyn This problem is related to WorkspaceObjectSelector (not sure who should be mentioned), I can see below pages on alpha have the same issue:
https://www.alpha.patricbrc.org/app/SeqComparison
https://www.alpha.patricbrc.org/app/ProteinFamily

**Comment by nconrad** [comment] 2017-07-25 21:28
should be addressed in https://github.com/PATRIC3/p3_web/pull/500 , but could maybe use some help testing, making sure entire form works.

**Comment by dawenx** [comment] 2017-07-26 13:12
Verified tree service page works as expected, but I did not submit it as I'm not sure whether the back-end is ready or not.

@olsonanl  I cannot reproduce the issue on + button for adding genome group, can you try again and let me know whether this issue is still there?

**Comment by olsonanl** [comment] 2017-07-26 13:20
It worked for me just now; I'll try again today on my other system and see if it does it again.

**Comment by dawenx** [comment] 2017-07-26 13:24
Thanks Bob, if there's a problem, I will blame WorkspaceObjectSelector :)

**Closed as completed** 2017-07-27 18:29 UTC
