### ISSUE TITLE
Having to log in repeatedly-then login disappears

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#491] opened 2015-10-02 12:05 UTC
This morning I have had to log in repeatedly, actually each time I try to save a new genome to my workspace.  And then this curious thing happened.  Look at the screenshot.  It doesn't show me as being logged in, and yet it shows my groups in the PFS.
![screen shot 2015-10-02 at 8 03 17 am](https://cloud.githubusercontent.com/assets/11475316/10246127/60a7f30a-68dc-11e5-8c23-4855fc7cba7b.png)

**Comment by mshukla1** [comment] 2015-10-19 18:12
Dustin, any follow up on this? 

Close it the problem can not be reproduced or fixed already/

**Comment by mshukla1** [comment] 2016-02-26 13:15
Looks like this is no longer an issue, or at least not seen in a while.

**Closed by mshukla1** 2016-02-26 13:15 UTC
Labels: bug, URGENT
