### ISSUE TITLE
Link vs. no links - in boxes

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#725] opened 2016-07-26 15:14 UTC
None of search and explore are links, but other boxes have live links

<img width="943" alt="screen shot 2016-07-26 at 10 13 49 am" src="https://cloud.githubusercontent.com/assets/8005288/17143673/b9e25ce4-5319-11e6-9ef1-c4ef9f1321c2.png">

**Comment by dmachi** [comment] 2016-07-27 03:23
Styling hasn't been completed on this yet, closing as a duplicate of #722

**Closed by dmachi** 2016-07-27 03:23 UTC
