### ISSUE TITLE
Show Toolbar problem

### ISSUE THREAD

**Issue by disz** [PATRIC3/patric3_website#217] opened 2015-06-04 14:42 UTC
I have a view that doesn't show columns for data and I don't know why. I clicked show toolbar and it added a row of stuff I don't want. I can't get rid of it, clicking again on show toolbar adds more rows.

Dragging images into this window doesn't work. I selected an image I saved, dunno if that is working or not either.

![screen shot 2015-06-04 at 9 40 21 am](https://cloud.githubusercontent.com/assets/5824759/7986536/c0c2906c-0a9d-11e5-96d8-85f263c9dead.png)

**Comment by mshukla1** [comment] 2015-06-09 19:28
Terry, I can not reproduce this behavior in chrome/firefox/safari. Please specify the browser/od you are using and show it to me next time we meet.

**Comment by hyoo** [comment] 2017-05-11 16:42
I am closing this ticket because
- we cannot reproduce for a while
- and this specific bug is on the old website that we plugged out

**Closed by hyoo** 2017-05-11 16:42 UTC
Labels: help wanted
