### ISSUE TITLE
Selecting reads from assembly and RNA-Seq pop-up window does not auto-fill the reads box

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2094] opened 2018-08-17 16:23 UTC
There are some issues with adding fastq files from workspace.  They select them from the pop-up window, click okay, and the pop-up closes.  But the name does not appear in the readfile box!     Users are having to go back and try several times.  Sometimes you can see it in the drop-down box, but not auto-filled

**Comment by dawenx** [comment] 2018-09-20 18:00
sorry for the delay response on this, but i have hard time to reproduce it. @ARWattam do you know what kind of OS/browser? 

@nconrad is this the same odd problem we ran into a couple months ago? i remember you fixed it in WOS.deselect event, is that the same thing?

**Comment by nconrad** [comment] 2018-09-20 18:15
I have no idea what is happening this time.  I made a number of changes and all issues were resolved as far as I know.   I'm not able to replicate either.

**Comment by dawenx** [comment] 2018-10-25 15:18
this might relates to #2142

**Comment by dawenx** [comment] 2019-02-08 19:45
since it has been for several months since last comment and we do not hear similar complaint, i will go ahead to close this issue.

**Closed as completed by dawenx** 2019-02-08 19:45 UTC
Labels: Service: Others
