### ISSUE TITLE
Logout while still in workspace leaves confused state?

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#64] opened 2015-03-19 23:55 UTC
I THINK this is the same on all browsers, but I won't swear to it.  I am specifically documenting Chrome / Mac

If I login and go to Workspace: Home and then logout, I get bounced back to the homepage, but the WORKSPACE:HOME is still there in the blue bar.   A reload will get rid of it (sometimes?  maybe depending on how many times I logged in?)

HOWEVER 2 issues
1) while it is still there on the blue bar, if I do browser back arrow, then I am back in my workspace and logged in (it says Welcome rwill1, and I can navigate my workspace and open genome groups).

2) while it is still there on the blue bar, if I click on WORKSPACE: HOME>, then it takes me to www.beta.patricbrc.org/workspace  and a blank page (except the headers/footers are there). (with no WORKSPACE: HOME> on the blue bar).   So now I try to login again, and I get to the login screen in the main browser page, not as a modal (I think I sent a screenshot of this before, URL is user.beta.patricbrc.org/login?application_id=patric3) and if I try logging in there, I get to www.beta.patricbrc.org/auth/callback - and a totally blank page - no headers, no nothing

**Comment by dmachi** [comment] 2015-03-20 00:00
1. probably happens because when you hit the back button it just redisplays the page without actually reloading it.  Though we'll need to check on it...somehow it still has your token and thats why workspace can still be accessed.

2. Is really a duplicate of #53 . When you visit a workspace or app page while not logged in, it should automatically show you a dialog.  This is failing, the page isn't loading completly, so the login link is just taking you directly to the login page when you click it.

**Comment by dmachi** [comment] 2015-03-20 04:53
I've solved #53. Can you test and see how it impacts #1 for you?

**Comment by rwill1** [comment] 2015-03-20 05:41
#1 still has the same behavior for me on beta.   logout and then browser backarrow gets me back into a logged in state.   I'm not sure that I would triage this as a Must Fix for the release.

**Comment by dmachi** [comment] 2015-03-20 14:27
I've put a fix in for this in beta that fixes this issue.

**Closed by dmachi** 2015-03-20 14:27 UTC
