### ISSUE TITLE
Having a hard time figuring out how to remove a genome from an established genome group

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1099] opened 2016-10-16 13:51 UTC
On production, I can easily click a genome and remove it using the remove icon:
<img width="1098" alt="screen shot 2016-10-16 at 9 50 01 am" src="https://cloud.githubusercontent.com/assets/11475316/19417888/fb8a34ee-9385-11e6-96f8-2454cf34ff36.png">

This doesn't seem to be available on beta...all I can do is create a group or view the genome:
<img width="1164" alt="screen shot 2016-10-16 at 9 50 55 am" src="https://cloud.githubusercontent.com/assets/11475316/19417891/2576481a-9386-11e6-8b95-42dedf83f85b.png">

**Comment by mshukla1** [comment] 2016-10-16 18:02
The problem is that we have two different views showing list of members in a genome group: 

1. When I double click on the genome group name in the workspace. 
This is the same page we have on the production site. From here, 
I can select a member and remove it from the group. 



2. When you select a genome group name in the workspace and click on the genome group view icon. 
This takes you to a genome list view which has the same tools as any other genome list, hence remove 
from group icon is missing. 



I do agree that this is confusing for the users and need to be addressed. My suggestion is to add group 
management actions in the second view above. 

-Maulik

**Comment by mshukla1** [comment] 2016-10-18 01:29
The problem is that we have two different views showing list of members in a genome group:
1. When I double click on the genome group name in the workspace.
   This is the same page we have on the production site. From here,
   I can select a member and remove it from the group.

<img width="1131" alt="screen shot 2016-10-16 at 12 59 05 pm" src="https://cloud.githubusercontent.com/assets/1236463/19419636/9017d9e8-93a1-11e6-9a4c-c28fdd040476.png">
1. When you select a genome group name in the workspace and click on the genome group view icon.
   This takes you to a genome list view which has the same tools as any other genome list, hence remove
   from group icon is missing.

<img width="1173" alt="screen shot 2016-10-16 at 12 59 22 pm" src="https://cloud.githubusercontent.com/assets/1236463/19419635/89e35b6a-93a1-11e6-862c-a52467d3e1a4.png">

I do agree that this is confusing for the users and need to be addressed. My suggestion is to add group
management actions in the second view above.

**Comment by mshukla1** [comment] 2016-10-18 01:31
On a second though, should we even have the first page (above)? When I double click on a group name, should't it take me to the group overview / landing page ?

**Comment by dmachi** [comment] 2016-12-01 18:45
This ticket was duplicated in the discussion of removing the workspace group drilldown and adding the remove button to the GenomeGroup view.  These have been completed. Closing this ticket.

**Closed as completed by dmachi** 2016-12-01 18:45 UTC
Labels: Enhancement
