### ISSUE TITLE
Can somebody PLEASE tell me how many files are in this workspace directory

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2170] opened 2019-01-11 15:23 UTC
This drives me nuts.  Its like the only table on the whole website that doesn't show you how many rows are displayed.

![image](https://user-images.githubusercontent.com/7661533/51042475-07110b00-1582-11e9-917b-f950975b18b5.png)

This is what I need.
![image](https://user-images.githubusercontent.com/7661533/51042724-9dddc780-1582-11e9-9cc4-87563363daa2.png)

**Comment by nconrad** [comment] 2019-01-11 19:23
Duplicate of #2150 & #1839, so i'm closing.  I marked it as higher priority, but similar to dropbox, you can select the visible items to get a count.  I think the confusion is coming from switching between search and the workspaces.

**Closed as completed by nconrad** 2019-01-11 19:23 UTC
