### ISSUE TITLE
Genome Browser: not displayed for private genomes!

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#929] opened 2016-09-07 19:44 UTC
I tried to load genome browser for several of my private genomes, and nothing was displayed. 
...or perhaps, it it taking too long, I can't tell the difference! 

<img width="1119" alt="screen shot 2016-09-07 at 2 43 35 pm" src="https://cloud.githubusercontent.com/assets/1236463/18326025/90a0a2ac-7509-11e6-99f1-5018e0ee7a70.png">

<img width="1275" alt="screen shot 2016-09-07 at 2 45 40 pm" src="https://cloud.githubusercontent.com/assets/1236463/18326085/cc1ad56e-7509-11e6-8afa-7f6729b400a1.png">

**Comment by dmachi** [comment] 2016-10-12 19:24
Duplicate of #953

**Closed by dmachi** 2016-10-12 19:24 UTC
Labels: bug
