### ISSUE TITLE
Output name in genome annotation confuses users

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#303] opened 2015-06-16 15:41 UTC
We have had a user put the specific strain identifier in the output name, and not in Organism name.  There she just used genus and species, and thus lost her strain designation.  What is the excellent reason for making the users write the name twice into two separate boxes on the same input box?

**Comment by olsonanl** [comment] 2015-08-04 19:40
closed as duplicate of #307

**Closed by olsonanl** 2015-08-04 19:40 UTC
Labels: duplicate, Services
