### ISSUE TITLE
RNA-seq job results page - if you go forward, and then use back arrow, the browser icon disappears in upper right corner

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2216] opened 2019-03-08 09:55 UTC

**Comment by dawenx** [comment] 2019-03-18 13:27
@ARWattam can you use an experiment in public workspace to take 2 screenshots on the problem you reported? thanks!

**Comment by mshukla1** [comment] 2019-04-13 16:01
I tried this several possible ways and I can't reproduce the problem. Hence, Closing the ticket.

**Closed as completed by mshukla1** 2019-04-13 16:01 UTC
Labels: Service: RNA-seq
