### ISSUE TITLE
Can't download any data for new genomes from Protein Family Sorter

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#546] opened 2015-11-23 15:54 UTC
I tried to get data from the PFS table view:
![screen shot 2015-11-23 at 10 51 02 am](https://cloud.githubusercontent.com/assets/11475316/11341433/71865a00-91d0-11e5-9f71-980e09b21179.png)

But when I download to excel, I see an empty sheet except for the column heads:
![screen shot 2015-11-23 at 10 51 09 am](https://cloud.githubusercontent.com/assets/11475316/11341460/8ba6a854-91d0-11e5-9685-c2423feaa449.png)

**Comment by hyoo** [comment] 2015-11-30 16:20
Sorry, I cannot reproduce this issue. It works for me. Would you try again since you recently cleared your cache?

![pfs](https://cloud.githubusercontent.com/assets/1236467/11477081/35257dbe-9754-11e5-8ddc-df49a5adef50.png)

**Comment by hyoo** [comment] 2016-10-14 16:13
this is not related to the beta.

**Comment by hyoo** [comment] 2017-01-06 20:53
this is old website and not able to reproduce. closing this ticket.

**Closed by hyoo** 2017-01-06 20:53 UTC
Labels: bug
