### ISSUE TITLE
Job submission: file selection dropdown, make it alphabatical

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1123] opened 2016-10-18 19:05 UTC
Currently, it is by created/modified date, which makes it harder to find files, when you have lot of them. 

-Maulik

**Comment by mshukla1** [comment] 2016-10-27 21:36
#1175

**Comment by dmachi** [comment] 2016-12-01 18:35
Duplicate of #1175, closing.

**Closed as completed by dmachi** 2016-12-01 18:35 UTC
Labels: Enhancement
