### ISSUE TITLE
All genomes not being saved to genome group

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#667] opened 2016-06-08 13:42 UTC
I was in the Pathway EC page and created a group that should have had 171 members (see screenshot)
![screen shot 2016-06-08 at 9 38 31 am](https://cloud.githubusercontent.com/assets/11475316/15896165/11f6239e-2d5d-11e6-845c-c8f86102b30d.png)
 But when I saved them, only 100 of the 171 showed up (see screenshot).  
![screen shot 2016-06-08 at 9 38 48 am](https://cloud.githubusercontent.com/assets/11475316/15896177/239506ba-2d5d-11e6-96ef-c6d85265d6b5.png)

Most discouraging.  I keep running into these small issues that make my life miserable.

**Comment by mshukla1** [comment] 2016-06-08 13:52
I can reproduce the same problem. Below is the URL for the pathway page from where I created genome group. 

https://www.patricbrc.org/portal/portal/patric/CompPathwayTable?cType=taxon&cId=1716&algorithm=PATRIC&ec_number=#aP0=1&aP1=1&aP2=1&aT=0&alg=PATRIC&cwEC=true&cwP=false&pId=&pClass=&ecN=2.7.7.10 <https://www.patricbrc.org/portal/portal/patric/CompPathwayTable?cType=taxon&cId=1716&algorithm=PATRIC&ec_number=#aP0=1&aP1=1&aP2=1&aT=0&alg=PATRIC&cwEC=true&cwP=false&pId=&pClass=&ecN=2.7.7.10>

**Comment by mshukla1** [comment] 2016-06-08 14:05
Some more details to help debug the problem.

I tried to create the same genome group by selecting all the genes from the pathway genes tab and then 
saving them as genome group, I got 100 genomes instead of 172. 

Then, I tried to do the same from the feature table, by searching for the same EC number, selecting features, 
and saving as genome group. Again, got 100 instead of 172. 
https://www.patricbrc.org/portal/portal/patric/FeatureTable?cType=taxon&cId=1716&featuretype=&annotation=PATRIC&filtertype=#aP0=1&fT=CDS&alg=PATRIC&filter=&kW="2.7.7.10"&key=1465394407393 <https://www.patricbrc.org/portal/portal/patric/FeatureTable?cType=taxon&cId=1716&featuretype=&annotation=PATRIC&filtertype=#aP0=1&fT=CDS&alg=PATRIC&filter=&kW=%222.7.7.10%22&key=1465394407393>

So, I think the problem is with the "saving features as genome groups” functionality in general and not 
specific to the pathway tab.

**Comment by hyoo** [comment] 2016-06-08 14:13
do you have a group with more than 100 genomes? then, can you see them correctly?
I am wondering whether it is a display problem (has all the genomes but just showing first 100) or saving problem (it claims 172 genomes, but actually having 100 genomes, which is more scary case).

**Comment by mshukla1** [comment] 2016-06-08 14:17
Yes, I do have some genome groups in my workspace with more than 100 genomes and they are displayed correctly. 
Though, they most likely were generated directly from genome list page.

When saving features as genome group, somehow it gets only 100 genomes, must be limit of number 
of records / facet values returned from solr/API. 

-Maulik

**Comment by mshukla1** [comment] 2016-06-08 14:23
Harry is busy preparing for the Demo Tomorrow. He will look into the problem later in the week, 
after the demo. 

-Maulik

**Comment by hyoo** [comment] 2016-06-13 16:59
this is fixed and available on beta and production.

**Comment by mshukla1** [comment] 2016-10-11 20:42
fixed on production/.

**Closed by mshukla1** 2016-10-11 20:42 UTC
Labels: fixed
