### ISSUE TITLE
Is MLST assignment broken?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#556] opened 2015-12-03 00:22 UTC
A user wrote in complaining about the MLSTs assigned by PATRIC.  He didn't understand what they meant.  I don't work with MLSTs too much myself, but something doesn't look right to me, either.  Here's what it looks like:
![screen shot 2015-12-02 at 7 17 06 pm](https://cloud.githubusercontent.com/assets/11475316/11548421/13ebd5f8-992a-11e5-896d-ec945830c42e.png)

**Comment by mshukla1** [comment] 2016-02-24 22:42
No, the assignment is not broken. This is how it was always assigned by the MLST pipeline. However, I agree that it is hard to say what it means or how to interpret it. Also, there is nothing you can do with it, 
or there are no tools to display/visualize/analyze MLST data. Something to with for in future. 

Given it is not a bug, closing the ticket. 

-Maulik

**Closed by mshukla1** 2016-02-24 22:42 UTC
