### ISSUE TITLE
data landing pages

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#403] opened 2015-08-17 21:01 UTC
jquery's $.scrollTo is not a function when clicking on the topics 'Download' 'Tools' etc.

**Comment by hyoo** [comment] 2015-08-25 14:28
Which browser are you using? I checked this function is working on chrome, safari, and firefox.

**Comment by hyoo** [comment] 2015-08-25 15:32
After talking to Andrew, we think this is more likely due to the firewall issue on their (Mayo institute) side. He observed this problem when he was in the workshop and he could not reproduce the problem on his machine, but was able to observe two of participants laptops. 

we are using google CDN for jQuery lib as below, and we guess their network (or some security software on their laptop) blocked the request. This explains the error message "is not a function", which means the function is not defined due to the absence of jQuery lib.

https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js

I am closing this issue and we will revisit when we migrate to nodeJS version.

**Closed by hyoo** 2015-08-25 15:32 UTC
Labels: Website / UI
