### ISSUE TITLE
Feature List: 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#986] opened 2016-10-06 15:50 UTC
Version: 3.2.9 beta
URL: 
https://www.beta.patricbrc.org/view/GenomeList/?keyword(KPN1934ec)#view_tab=features&filter=and(eq(annotation,%22PATRIC%22),or(eq(feature_type,%22CDS%22),eq(feature_type,%22repeat_region%22)),keyword(573.3168.con.0001))
User ID: KPNs_4_Houston

The coordinates of repeat regions (start and end) are not displayed in the 
feature table.

==> I think the problem here is that added columns are not displayed when there are already enough columns displayed in the table. This is problematic, because there isno indication given to the user as to why the selected columns are not displayed. 

-Maulik

**Comment by dmachi** [comment] 2016-10-06 16:18
Duplicate of #979

**Closed as completed by dmachi** 2016-10-06 16:18 UTC
Labels: Bug, Critical

**Comment by mshukla1** [comment] 2016-10-11 19:51
verified on beta.
