### ISSUE TITLE
Phylogeny tab empty

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#824] opened 2016-08-04 00:55 UTC
"Phylogeny" tab appears empty for all taxonomic  groups in this string below, including for the root node ('Bacteria').  And for any other cyanobacteria I tested

Bacteria » Terrabacteria group » Cyanobacteria/Melainabacteria group » Cyanobacteria » Oscillatoriophycideae » Chroococcales » Cyanothece » Cyanothece sp. PCC 8801 ( 1 Genomes ) 

<img width="1016" alt="phylogeny_empty" src="https://cloud.githubusercontent.com/assets/20665963/17386844/0a84fea4-59b4-11e6-9f5c-44645b0089c7.png">

**Comment by dmachi** [comment] 2016-09-01 13:55
Duplicate of #762.

**Closed by dmachi** 2016-09-01 13:55 UTC
