### ISSUE TITLE
Congratulations, JBrowse is on the web!

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1089] opened 2016-10-13 16:53 UTC
I tried to load the genome browser for a private genome for the following feature:

fig|573.3870.peg.3674 | Transposase, IS4

![image](https://cloud.githubusercontent.com/assets/7661533/19358452/9a26d316-913b-11e6-95fe-0ada57365960.png)

**Comment by dmachi** [comment] 2016-10-13 17:09
Duplicate of #953

**Closed as completed by dmachi** 2016-10-13 17:09 UTC
