### ISSUE TITLE
counting error on jobs page

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2100] opened 2018-08-20 18:37 UTC
I have 47 failed jobs, but the number counted in the top right says there are 9 failed jobs.

![image](https://user-images.githubusercontent.com/7661533/44359639-17630500-a47e-11e8-8bde-a8b0a31c396d.png)

**Comment by nconrad** [comment] 2018-08-20 19:11
This is a duplicate of https://github.com/PATRIC3/patric3_website/issues/2060 .

The issue is 38 of those jobs have `awe_status` marked as "completed" or "in-progress",  yet 47 have `status` marked as "failed".

**Comment by mshukla1** [comment] 2019-04-17 16:36
#2235 dumplicate

**Closed as completed by mshukla1** 2019-04-17 16:36 UTC
Labels: UI: Jobs
