### ISSUE TITLE
Jobs list: incorrect counts for job status

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2235] opened 2019-04-04 01:09 UTC
Neal, 

There are inconsistencies in the job status in the job list and the job status counts displayed above the list. Look at the screenshot below from one of the users. He has five failed jobs. However, above the job lists it says 5 completed and 0 failed. The same goes for the job status in the bottom right corner. 

Please see if you can resolve this for March Release. 

-Maulik

<img width="1678" alt="Screen Shot 2019-04-03 at 8 09 10 PM" src="https://user-images.githubusercontent.com/1236463/55522873-5f6d1b80-564c-11e9-9b54-9a1ab93919c0.png">

**Comment by nconrad** [comment] 2019-04-04 01:23
This is a duplicate of https://github.com/PATRIC3/patric3_website/issues/2060 .  @olsonanl any chance of fixing the count returned by `AppService.query_task_summary`?  It's been reported a few times now.

**Comment by mshukla1** [comment] 2019-04-16 15:00
Neal: I think AppService.query_task_summary is returning awe_status counts instead of status counts.

@olsonanl, is there a way to get job status?

**Comment by olsonanl** [comment] 2019-04-16 15:25
It requires fiddling. If it's a big problem I can look into it; it's a problem that will likely go away entirely with the new scheduler.

**Comment by mshukla1** [comment] 2019-04-16 15:28
Given the issue has been open for a while now, this is not urgent or critical.

I would wait until we have the new scheduler.

**Comment by nconrad** [comment] 2020-08-04 17:11
I believe @olsonanl has fixed this last year as part of the new scheduler.  Closing.

**Closed as completed by nconrad** 2020-08-04 17:11 UTC
Labels: UI: Jobs
