### ISSUE TITLE
genome annotation validation failing again (Cannot Submit)

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#197] opened 2015-06-02 18:14 UTC
earlier today I could fight this into working but now I am failing utterly.

Here is a screencast of the failure I keep getting. 

 http://youtu.be/W7aRzQ7WVaM 

here it is with the error console up. again we are seeing that "text not defined" error. This latter session was done in firefox on mac after clearing caches and going anew to the application page.

http://youtu.be/ZfbXr_h3bxM

**Comment by dmachi** [comment] 2015-06-05 15:56
This has been resolved and is also a duplicate of the #193

**Closed by dmachi** 2015-06-05 15:56 UTC

**Comment by olsonanl** [comment] 2015-06-05 16:45
much better.
