### ISSUE TITLE
New folder icon creates unnamed file in workspace.

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#122] opened 2015-03-26 21:54 UTC
When selecting new folder in this upload dialog, an empty nameless file is created in the workspace.

![screen shot 2015-03-26 at 5 50 51 pm](https://cloud.githubusercontent.com/assets/991769/6857970/f90b7a18-d3e0-11e4-9500-bdfe1d1fc23f.png)

**Comment by dmachi** [comment] 2015-03-27 00:17
Duplicate of #120.  Will get fixed tonight.

**Closed by dmachi** 2015-03-27 00:17 UTC
