### ISSUE TITLE
Enhancement to Proteome Comparison-directionality of uni hits

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1230] opened 2016-11-04 19:55 UTC
We have had a user request for this.  We should include a column in the download that has the following designation
bi (<=>)
uni (<=)
uni (=>)

**Comment by levinas** [comment] 2016-11-26 01:58
We only have bi (<=>) and uni (=>). This is because in the download table we see the similarity hits from the perspective of the reference genome, and each reference gene is only listed once. 

That said, I've changed bi to "bi (<=>)" and uni to "uni (=>)". 
https://github.com/TheSEED/app_service/pull/58

**Comment by hyoo** [comment] 2017-05-01 21:25
@ARWattam or @levinas Would you verify whether this is deployed on production and close it?

**Comment by hyoo** [comment] 2017-05-01 22:06
confirmed in production

**Closed as completed by hyoo** 2017-05-01 22:06 UTC
Labels: Enhancement, Fixed, Service: Others
