### ISSUE TITLE
AMR Panel Summary - blank

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#759] opened 2016-07-26 15:44 UTC
<img width="753" alt="screen shot 2016-07-26 at 10 44 25 am" src="https://cloud.githubusercontent.com/assets/8005288/17144892/fa687f56-531d-11e6-93b2-880ad324d557.png">

**Comment by dmachi** [comment] 2016-07-27 03:15
Closed. Duplicate of #760

**Closed by dmachi** 2016-07-27 03:15 UTC
