### ISSUE TITLE
BLAST renders program selection box wrong

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1016] opened 2016-10-10 19:21 UTC
I am currently trying to select blastn as the option and I get the selection window floating down the screen.  I'm on firefox

<img width="824" alt="screen shot 2016-10-10 at 2 20 27 pm" src="https://cloud.githubusercontent.com/assets/7661533/19248287/bf50e508-8ef4-11e6-82f1-90b2bdc21520.png">

**Comment by jimdavis1** [comment] 2016-10-10 19:22
<img width="793" alt="screen shot 2016-10-10 at 2 21 42 pm" src="https://cloud.githubusercontent.com/assets/7661533/19248328/e8491d5e-8ef4-11e6-906b-a3a06e6f3aa9.png">

**Comment by hyoo** [comment] 2016-10-12 20:40
I cannot reproduce this problem. This seems like a browser bug. 
I am on firefix 49.0.1. Which version are you using?

**Comment by hyoo** [comment] 2016-10-21 15:50
duplicate #1016

**Comment by hyoo** [comment] 2016-10-21 15:51
I am closing this one and will address this issue on #1152

**Closed as completed by hyoo** 2016-10-21 15:51 UTC
