### ISSUE TITLE
Selection checkboxes missing on gene list table in Transcriptomics tab

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1081] opened 2016-10-13 15:15 UTC
https://www.beta.patricbrc.org/view/TranscriptomicsExperiment/?eq(eid,(697868))

![screen shot 2016-10-13 at 11 13 30 am](https://cloud.githubusercontent.com/assets/3188570/19354907/670f332e-9136-11e6-91af-334be7ed7cc3.png)

**Comment by dmachi** [comment] 2016-10-13 15:23
Duplicate of #700.

**Closed as completed by dmachi** 2016-10-13 15:23 UTC
