### ISSUE TITLE
Clicking on protein family from feature table reveals genes from weird genome that was not part of original selection

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1036] opened 2016-10-10 19:58 UTC
I had a group of Escherichia coli:
<img width="1401" alt="screen shot 2016-10-10 at 3 53 16 pm" src="https://cloud.githubusercontent.com/assets/11475316/19249167/041bbafc-8f02-11e6-952e-73b454dda6bb.png">
Then I double clicked on a specific column to see all the genes:
<img width="817" alt="screen shot 2016-10-10 at 3 52 33 pm" src="https://cloud.githubusercontent.com/assets/11475316/19249195/280b8870-8f02-11e6-8a55-de09e8167fa8.png">
When I clicked on the Features tab, I saw a genome that was not part of my original selection:
<img width="1117" alt="screen shot 2016-10-10 at 3 53 06 pm" src="https://cloud.githubusercontent.com/assets/11475316/19249213/502ee93c-8f02-11e6-8ceb-3e044b861fb6.png">

**Comment by ARWattam** [comment] 2016-10-10 19:58
And, by the way, the Feature List Overview never loaded:
<img width="829" alt="screen shot 2016-10-10 at 3 52 42 pm" src="https://cloud.githubusercontent.com/assets/11475316/19249230/6687bb78-8f02-11e6-8818-67e16718b004.png">

But that's minor compared to getting the wrong genome!

**Comment by hyoo** [comment] 2016-10-11 16:15
This is due to #1055. and duplicate of #1038

**Closed as completed** 2016-10-11 21:23 UTC
Labels: Bug, Critical
