### ISSUE TITLE
Genome Annotation app required param confusion

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#277] opened 2015-06-10 22:25 UTC
The Genome Annotation app does this weird thing where the "output name" is highlighted after populating the org name and taxon id.  However, the "output folder" field is not highlighted, even though that is also required.

![screen shot 2015-06-10 at 5 12 48 pm](https://cloud.githubusercontent.com/assets/1194246/8095664/a4503694-0f95-11e5-9991-2a2b868a0a9a.png)

**Comment by olsonanl** [comment] 2015-08-05 20:38
This is another duplicate of #307. Closing as such.

**Closed** 2015-08-05 20:39 UTC
Labels: Services
