### ISSUE TITLE
Assembly service: SRR accession input failed

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1879] opened 2018-02-09 19:16 UTC
Unable to enter a SRR accession number as an input.

![screen shot 2018-02-09 at 2 14 16 pm](https://user-images.githubusercontent.com/6361802/36045470-d3c729c8-0da3-11e8-8e01-31624d581f39.png)

**Comment by mshukla1** [comment] 2018-02-09 20:58
I got the same error when I clicked the arrow to select the library. 

-Maulik

**Comment by dawenx** [comment] 2018-08-16 20:15
@maovt @mshukla1 i used the SRR info from Chunhong's screenshot and it works for me. can you check it to see whether the problem is still there?

**Comment by mshukla1** [comment] 2018-08-16 20:41
I believe this is an old ticket just after we made the SRR accession box available. 

It is working for me now and we have used it in numerous workshops. Closing the ticket.

**Comment by chmao1** [comment] 2018-08-17 14:41
I tested this and the job failed due to the space issue. Here is the error message:

Running /home/fangfang/programs/sratoolkit.2.8.2-1-ubuntu64/bin/fastq-dump --outdir /scratch/tmp/0mww7vl24a --split-3 --dumpbase --clip --skip-technical --read-filter pass SRR6691689
\@submit_cmd = $VAR1 = [
          'ar-run',
          '-r',
          'auto',
          '--pair',
          '/scratch/tmp/0mww7vl24a/SRR6691689_pass_1.fastq',
          '/scratch/tmp/0mww7vl24a/SRR6691689_pass_2.fastq'
        ];
Running ar-run -r auto --pair /scratch/tmp/0mww7vl24a/SRR6691689_pass_1.fastq /scratch/tmp/0mww7vl24a/SRR6691689_pass_2.fastq
Error submitting run. Run command=ar-run -r auto --pair /scratch/tmp/0mww7vl24a/SRR6691689_pass_1.fastq /scratch/tmp/0mww7vl24a/SRR6691689_pass_2.fastq, stdout:

stderr:
Shock error: Upload failed: 400. [u'err@node_CreateNodeUpload: mkdir /disks/shock/Shock/data/f6/e4/36: no space left on device']

**Closed as completed** 2019-04-08 12:53 UTC
Labels: Bug, Fixed, Service: Assembly
