### ISSUE TITLE
RNAseq crash on demo data

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#356] opened 2015-07-21 18:19 UTC
Workshop user's job 0ec13176-a7b5-4d52-989c-34ce992c4012 crashed; she used the sample files from the website but a different reference (1455315.3)

```
Error running cmd=java -Xmx1200m -cp /disks/patric-common/runtime/lib/Rockhopper.jar Rockhopper -SAM -TIME -p 1 -o /scratch/tmp/wsak7uta9f/Rockhopper -g /scratch/tmp/wsak7uta9f/1455315.3/JICJ01000001,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000002,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000003,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000004,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000005,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000006,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000007,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000008,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000009,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000010,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000011,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000012,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000013,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000014,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000015,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000016,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000017,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000018,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000019,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000020,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000021,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000022,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000023,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000024,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000025,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000026,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000027,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000028,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000029,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000030,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000031,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000032,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000033,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000034,/scratch/tmp/wsak7uta9f/1455315.3/JICJ01000035 -L MHB,AMI,CIP,COL,MERO /scratch/tmp/wsak7uta9f/MHB_R1.fq.gz%/scratch/tmp/wsak7uta9f/MHB_R2.fq.gz /scratch/tmp/wsak7uta9f/AMI_75_1.fq.gz%/scratch/tmp/wsak7uta9f/AMI_75_2.fq.gz /scratch/tmp/wsak7uta9f/CIP_75_1.fq.gz%/scratch/tmp/wsak7uta9f/CIP_75_2.fq.gz /scratch/tmp/wsak7uta9f/COL_75_R1.fq.gz%/scratch/tmp/wsak7uta9f/COL_75_R2.fq.gz /scratch/tmp/wsak7uta9f/MERO_75_R1.fq.gz%/scratch/tmp/wsak7uta9f/MERO_75_R2.fq.gz, stdout:
Error - expecting 9 columns of gene information but found less than 9:	21517..22602	-				/	-		

stderr:
Exception in thread "main" java.lang.NullPointerException
	at Gene.isORF(Gene.java:165)
	at Genome.create_GFF_file(Genome.java:376)
	at Genome.<init>(Genome.java:76)
	at Rockhopper.<init>(Rockhopper.java:99)
	at Rockhopper.main(Rockhopper.java:908)
```

**Comment by olsonanl** [comment] 2015-07-21 20:59
I was able to repeat this crash by selecting that same alternate reference genome.

**Comment by aswarren** [comment] 2015-08-24 23:21
This appears to be another source code bug for Rockhopper which @levinas are going to address during the next meetup.

**Comment by aswarren** [comment] 2015-08-27 20:38
In trying to figure out what may be causing the crash I noticed that the GFF file being created through the API is slightly malformed due to a missing patric_id for this feature: 
https://www.beta.patricbrc.org/api/genome_feature/?q=genome_id:1455315.3%20AND%20start:21517%20AND%20annotation:PATRIC&rows=250&http_content-type=application/solrquery+x-www-form-urlencoded&http_accept=application/solr+json

**Comment by levinas** [comment] 2015-08-27 20:42
Thanks for spotting that.

**Comment by levinas** [comment] 2015-09-02 21:21
Looks like the feature with missing patric_id was the cause of the crash.

The job completed successfully after Maulik fixed the id.
https://www.patricbrc.org/workspace/workshopdemo@patricbrc.org/home/rnaseq_test/reproduce-issue356

We can close the issue.

**Closed** 2016-02-26 13:17 UTC
Labels: Services
