### ISSUE TITLE
Column selection needs to be alphabetized

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1786] opened 2017-11-13 14:20 UTC
![image](https://user-images.githubusercontent.com/7661533/32730072-82d64e2e-c84b-11e7-89d0-e4f913cc7f9c.png)

**Comment by zreyn** [comment] 2017-11-13 14:36
Note to whoever ends up working on this issue: the column ordering in this selection box is taken from the data grid, which determines the column ordering for the main display, download, and copy.  If this box needs to be alphabetized, it should only be alphabetized locally/for this box.

**Comment by hyoo** [comment] 2017-11-13 16:05
@zreyn is right, Column selection follows whatever the order that grid is configured. 

Column order is also manually crafted, by grouping/ordering in semantic order. Please talked to me or Maulik before make changes.

**Comment by rkenyon** [comment] 2018-08-03 20:24
Jim triage comment: Low.  The table column ordering follows a format that only harry and maulik understand.  I find myself staring at it for a long time to find the right fields.

**Comment by nconrad** [comment] 2019-04-19 15:39
I've looked into this before--I'll have to again. It is complicated because it would require some changes to the dojo library. 

The issue is the order of that list corresponds to the order we want columns to appear in the table (such as the order of the default columns).  Hence, we would have to build something in the dojo widget to use that order, but display the list in alphabetical order.

I'm going to tag @dmachi because I'm curious if he has already made some of the dojo code custom for this project?  If so, I can try hacking it.

**Comment by nconrad** [comment] 2019-05-09 23:16
I'm marking this as P4 for now.  There's this and a few more features requested from tables below, and so we may want to re-evaluate the table plugin.

- saving table state in localstorage (and ability return to "default" state)
- copy and paste of cells/columns/rows

**Closed as completed by nconrad** 2019-05-09 23:16 UTC
Labels: UI, PATRIC4
