### ISSUE TITLE
Loading private genome page doesn't work from workspace

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#316] opened 2015-06-17 20:26 UTC
When I click on the eye to view my private genome landing page, it looks like this:
![screen shot 2015-06-17 at 3 24 46 pm](https://cloud.githubusercontent.com/assets/11475316/8217826/2342c8e4-1505-11e5-91aa-2f9192b3f2a9.png)

When I do a global search for it and load it from the search page, it looks like this:
![screen shot 2015-06-17 at 3 26 20 pm](https://cloud.githubusercontent.com/assets/11475316/8217851/48747680-1505-11e5-890f-74a91bb82d17.png)

**Comment by mshukla1** [comment] 2015-06-19 14:32
Duplicate or related to #314

**Comment by dmachi** [comment] 2015-08-05 16:20
Closing as duplicate of #314

**Closed by dmachi** 2015-08-05 16:20 UTC
Labels: Workspace
