### ISSUE TITLE
Refresh needed to see newly updated files

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1517] opened 2017-05-18 14:11 UTC
At the tutorial today folks are having problems with assembly app uploads. The paired end library drop down was not populating, and if you went to the browser and selected a file (in the submission dialog), the file would not appear in the read file text box. Refreshing the page brought them in properly.

I seem to recall some discussion this week of refresh related bugs ... maybe something global changed?

**Comment by dawenx** [comment] 2017-05-18 19:27
Just a comment on filter refresh related bug. Not necessary related to this issue.

Pathway Tab used to have this kind of bug and the newly created (still under development) Subsystem Tab had this problem 2 weeks ago.

What happened in Pathway Tab (PathwaysContainer.js) was, in onSetState function, the condition to set selectedChildWidget was not correct, it used to be something like below:
 
if(this.tabContainer && this.tabContainer.selectedChildWidget && this._firstView && !this.tabContainer.selectedChildWidget.state){

What need to be set should be something like:

if(this.tabContainer && this.tabContainer.selectedChildWidget && this._firstView && this.tabContainer.selectedChildWidget.state != state){

I suspect any tab/widget with child tab/widget might have similar refresh issue if they come from a same base.

**Comment by dawenx** [comment] 2017-12-08 18:00
first, my comment on 05/18 has nothing to do with this issue.

second, with the latest fix on upload, newly upload files from the same tab should work now. but i'm aware of 'lack of refreshing' in service pages, i.e., if we upload a file from a different tab/window, we need to navigate to another folder and come back in order to see the newly upload file. 

@nconrad i can work on this issue if that's ok, but we probably need to discuss briefly to make sure what kind of refreshing behaviors are proper.

**Comment by dawenx** [comment] 2018-05-04 15:23
I cannot reproduce the problem now, maybe it has been fixed? @olsonanl can you verify?

**Comment by dawenx** [comment] 2018-07-17 14:28
I plan to close this ticket unless I hear someone's objection by EOD.

**Comment by olsonanl** [comment] 2018-07-17 15:18
I don't think I've seen this behavior lately. Will open a new ticket if I do.

**Comment by dawenx** [comment] 2018-07-17 17:48
Close this as we cannot reproduce it now.

**Closed as completed by dawenx** 2018-07-17 17:48 UTC
Labels: Enhancement, Unable to Reproduce
