### ISSUE TITLE
Some odd behavior adding in extra columns into workspace

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#605] opened 2016-03-01 00:39 UTC
I've run into this about 5 times today.  I click on a column that I want to see (AA length) and the column doesn't add in, but the header for the first row gets thicker.  I'll be unable to add in any columns and be forced to reload the workspace.
![screen shot 2016-02-29 at 7 37 28 pm](https://cloud.githubusercontent.com/assets/11475316/13413915/25f83f4c-df1c-11e5-9c50-80959fefc1be.png)
![screen shot 2016-02-29 at 7 37 18 pm](https://cloud.githubusercontent.com/assets/11475316/13413916/25f95daa-df1c-11e5-9c59-72094ec603bc.png)

**Comment by dmachi** [comment] 2016-03-24 17:39
I haven't been able to reproduce this problem.  Is it still happening for you?  Is it happening on multiple feature groups or just on a specific feature group?

**Comment by dmachi** [comment] 2016-03-29 15:54
Moving to new alpha release for now as I can't reproduce it yet.

**Closed** 2016-08-03 01:15 UTC
Labels: bug, question, Workspace
