### ISSUE TITLE
Still not right in loading from first gene in tables-beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1012] opened 2016-10-10 11:55 UTC
Many of the bacterial genomes have multiple contigs or chromosomes.  The sorting needs to be on the contig, and on the start site.  Brucella has 2 chromosomes and look at how this looks-
<img width="1122" alt="screen shot 2016-10-10 at 7 53 59 am" src="https://cloud.githubusercontent.com/assets/11475316/19235310/f7496376-8ebe-11e6-863f-16e5781f66b5.png">

**Comment by hyoo** [comment] 2016-10-10 14:46
This is related #1011 

original sorting condition was genome -> accession -> start position. But this conflicts to global search result where the match score takes order. 

I think we need to revert back to original sorting condition and global search override sorting order.

**Comment by dmachi** [comment] 2016-10-10 23:51
Duplicate of #1011 and at least one other ticket i can't seem to locate.

**Closed as completed by dmachi** 2016-10-10 23:51 UTC
Labels: Enhancement
