### ISSUE TITLE
Return button of the Browser 

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#773] opened 2016-07-26 16:00 UTC
Return button of the Browser does not work properly from every page, it seems
From some pages it takes pressing it twice to get back.  From some other pages it does not work at all.  I thought this issue was somehow connected to a user being logged-in .  So I registered and logged in, but the issue persisted

**Comment by dmachi** [comment] 2016-08-02 19:36
Duplicate of #676.  This won't be able to be solved in all cases, but we are trying to make it work as much as possible.

**Closed by dmachi** 2016-08-02 19:36 UTC
