### ISSUE TITLE
Changing to Significant Genes in Transcriptomics Heat map view does nothing

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#559] opened 2015-12-07 11:59 UTC
It should take away all the black boxes...instead nothing changes.
![screen shot 2015-12-07 at 5 58 07 am](https://cloud.githubusercontent.com/assets/11475316/11626342/a0f778dc-9ca7-11e5-97ac-e49cd15fd5d9.png)

**Comment by mshukla1** [comment] 2016-02-24 22:37
I tried it with couple of experiments and can not reproduce the problem, or at least for me it worked as expected. 

Just looking at the screenshot, it looks like you were working with a Brucella dataset you uploaded using either RNA-Seq or differential expression upload. Given that even after selecting significant genes, you still see 3562 genes, perhaps you may not have applied any log ratio/z-score cut-off. With out any cut-offs the list of significant genes would bve the same as all genes, hence changing the selection from dropdown would give you exactly the same view. 

I am closing the ticket, please reopen if you can reproduce the problem. 

-Maulik

**Closed by mshukla1** 2016-02-24 22:37 UTC
