### ISSUE TITLE
Bug in creating folder in workspace

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1371] opened 2016-12-11 17:14 UTC
If i click on the folder icon to create a folder to put an annotation job into, it creates a file and not a folder.

Actually, I waited a little bit, and it shows up as a folder even though the icon looks like a file. Weird.  Oh and also, when I did it in the proteome comparison tool, it flashed an orange box in the top left that said "error creating folder".

![image](https://cloud.githubusercontent.com/assets/7661533/21081767/fdbc5cae-bf92-11e6-80ff-68753484c5ed.png)

![image](https://cloud.githubusercontent.com/assets/7661533/21081762/e33a33d8-bf92-11e6-890c-809cb98de40b.png)

![image](https://cloud.githubusercontent.com/assets/7661533/21081760/ddc89f20-bf92-11e6-8488-132c35794999.png)

![image](https://cloud.githubusercontent.com/assets/7661533/21081778/406a455c-bf93-11e6-855b-d31e8b50b4eb.png)

**Comment by dmachi** [comment] 2016-12-11 17:17
Also unable to reproduce this issue.  The file icon shows up until a few seconds after I name, then when the folder creation is complete it gets moved to the normal portion of the list (instead of staying above “Parent Folder”) and its icon changes to a folder.  Something else weird must be going on in this case.

**Comment by dmachi** [comment] 2016-12-11 17:19
Actually in your screenshot I can see why this failed (though the failure behavior should be better).  You already have a folder called “E_coli_Anno” (look at the bottom of your second screenshot), so it fails to create a new folder and the display isn’t cleaned up afterwards.

**Comment by nconrad** [comment] 2017-09-06 17:18
With the latest workspace updates, the 'new folder' button gives a prompt, resolving these issues.

**Closed as completed by nconrad** 2017-09-06 17:18 UTC
Labels: UI: Workspace
