### ISSUE TITLE
file list dialog is too narrow

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#91] opened 2015-03-23 19:18 UTC
![screen shot 2015-03-23 at 3 16 28 pm](https://cloud.githubusercontent.com/assets/1236467/6788420/b32d98b4-d16f-11e4-8123-18b9a37ba80d.png)

**Comment by dmachi** [comment] 2015-03-23 21:15
Duplicate of #86

**Closed by dmachi** 2015-03-23 21:15 UTC
