### ISSUE TITLE
Expression import submit form clears fields partially after submission

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1379] opened 2016-12-13 19:55 UTC
![image](https://cloud.githubusercontent.com/assets/1236467/21156500/aa1cad10-c13b-11e6-8b3a-9cdedd333a8b.png)

Right after clicking "submit" it clears title, but all other fields are remaining. Not sure whether it is intended. May needs to clear all the fields or leave it so that user can review.

**Comment by dawenx** [comment] 2017-12-11 20:27
@hyoo when i tested it today w/ "debugging panel", i cannot reproduce the problem. can you double check to see whether the issue is still there? also, i only checked the codes briefly, it looks like this service uses onSubmit() function in AppBase class, so it's possible it's "fixed". :)

**Comment by hyoo** [comment] 2017-12-11 20:57
@dawenx i agree. Some pages were not inheriting AppBase. Just to double check, you have "submitted" your Job, right?

**Comment by aswarren** [comment] 2017-12-21 11:50
@hyoo @dawenx Pretty sure this is intended behavior since the experiment title is used to name the output which has to be unique from job to job. Clearing forces the user to enter a new name if they want to resubmit which will trigger the validation of the title relative to existing experiments.

**Comment by dawenx** [comment] 2017-12-21 16:00
@aswarren should we "fix" or close this issue then?

**Closed as completed** 2018-04-14 00:04 UTC
Labels: Enhancement
