### ISSUE TITLE
Search: cant search for features with /'/ prime

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#983] opened 2016-10-05 21:44 UTC
Version: 3.2.9 beta
URL: 
https://www.beta.patricbrc.org/view/GenomeList/?keyword(KPN1572ec)#view_tab=features&filter=and(eq(annotation,%22PATRIC%22),and(keyword(2%27-5),keyword(RNA),keyword(ligase%27)))
User ID: KPNs_4_Houston

I can't search for the following function in the feature table because of 
the single quotes: 2'-5' RNA ligase

**Comment by dmachi** [comment] 2016-10-06 01:37
Duplicate of #964

**Closed as completed by dmachi** 2016-10-06 01:37 UTC
Labels: Bug, Critical
