### ISSUE TITLE
Submitted 6 assembly jobs...got message that they were queued, but none appear on jobs page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1330] opened 2016-11-30 20:01 UTC
<img width="1416" alt="screen shot 2016-11-30 at 3 01 09 pm" src="https://cloud.githubusercontent.com/assets/11475316/20768950/eed2bf0e-b70d-11e6-8828-2ce51506b5c6.png">

**Comment by ARWattam** [comment] 2016-11-30 20:40
Jobs appeared about an hour after submitting them.  The delay isn't good
<img width="1173" alt="screen shot 2016-11-30 at 3 40 07 pm" src="https://cloud.githubusercontent.com/assets/11475316/20770334/5b1f8020-b713-11e6-9ecf-16351a0e9c58.png">

**Comment by dmachi** [comment] 2016-12-01 15:59
Duplicate of #1170. Closing.

**Closed as completed by dmachi** 2016-12-01 15:59 UTC
