### ISSUE TITLE
Genome browser appears not to be loading on private genome

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#956] opened 2016-10-02 20:48 UTC
I waited 5 minutes...never loaded
<img width="934" alt="screen shot 2016-10-02 at 4 46 24 pm" src="https://cloud.githubusercontent.com/assets/11475316/19023590/035d438a-88c0-11e6-8763-dffe12e8d366.png">

**Comment by hyoo** [comment] 2016-10-03 21:23
instrumentation.js:20 TypeError: Cannot read property 'name' of undefined(…) "TypeError: Cannot read property 'name' of undefined
    at _initialLocation (/js/JBrowse/Browser.js:187:37)
    at eval (/js/JBrowse/Browser.js:145:53)
    at signalListener (/js/dojo/Deferred.js:37:21)
    at signalWaiting (/js/dojo/Deferred.js:28:4)
    at Deferred.resolve (/js/dojo/Deferred.js:192:5)
    at eval (/js/p3/widget/GenomeBrowser.js:623:17)
    at eval (/js/dojo/_base/lang.js:385:55)
    at signalListener (/js/dojo/Deferred.js:37:21)
    at signalWaiting (/js/dojo/Deferred.js:28:4)
    at Deferred.resolve (/js/dojo/Deferred.js:192:5)
    ----------------------------------------
    rejected at signalDeferred (/js/dojo/Deferred.js:84:15)
    at signalListener (/js/dojo/Deferred.js:55:5)
    at signalWaiting (/js/dojo/Deferred.js:28:4)
    at Deferred.resolve (/js/dojo/Deferred.js:192:5)
    at eval (/js/p3/widget/GenomeBrowser.js:623:17)
    at eval (/js/dojo/_base/lang.js:385:55)
    at signalListener (/js/dojo/Deferred.js:37:21)
    at signalWaiting (/js/dojo/Deferred.js:28:4)
    at Deferred.resolve (/js/dojo/Deferred.js:192:5)
    at signalDeferred (/js/dojo/Deferred.js:81:15)
    ----------------------------------------
Error
    at Deferred.then.promise.then [as then](/js/dojo/Deferred.js:252:24)
    at eval (/js/JBrowse/Browser.js:142:41)
    at signalListener (/js/dojo/Deferred.js:37:21)
    at Deferred.then.promise.then [as then](/js/dojo/Deferred.js:258:5)
    at eval (/js/JBrowse/Browser.js:139:37)
    at signalListener (/js/dojo/Deferred.js:37:21)
    at signalWaiting (/js/dojo/Deferred.js:28:4)
    at Deferred.resolve (/js/dojo/Deferred.js:192:5)
    at eval (/js/p3/widget/GenomeBrowser.js:719:16)
    at notify (/js/dojo/_base/Deferred.js:187:23)"

**Comment by dmachi** [comment] 2016-10-06 01:23
Duplicate of #953

**Closed as completed by dmachi** 2016-10-06 01:23 UTC
Labels: Bug
