### ISSUE TITLE
Bug in transcriptomics data

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#424] opened 2015-09-02 19:27 UTC
Rebecca and I were looking at the transcritpomics page for fig|511145.12.peg.1  and found a bug.  The histogram shows different numbers when you filter the table.  For instance we originally saw 117 experiments with a log ratio of -2 (see first image) and then we filtered on log ratio of 2 and only saw 84 (See second image)

<img width="1020" alt="screen shot 2015-09-02 at 2 23 26 pm" src="https://cloud.githubusercontent.com/assets/7661533/9641896/c49d2ddc-517e-11e5-86c4-680040bc2e4d.png">

<img width="608" alt="screen shot 2015-09-02 at 2 23 45 pm" src="https://cloud.githubusercontent.com/assets/7661533/9641904/cd0bdc0c-517e-11e5-9dba-dfde569632da.png">
.

**Comment by mshukla1** [comment] 2016-10-25 17:21
@maovt, This issue still persists on the beta site. I think the the chart below is somewhat misleading. There are 117 comparisons with log ratio <= -1.5 and there are 84 with log ration <= -2.0. 

<img width="506" alt="screen shot 2016-10-25 at 12 20 42 pm" src="https://cloud.githubusercontent.com/assets/1236463/19696632/9a50738a-9aad-11e6-8a95-d3240da573f7.png">

**Comment by chmao1** [comment] 2016-10-27 15:52
@aswarren This bug is caused by using gt and lt instead of gte and lte. However, gte and lte is not implemented in api. Could you add these in api? Thanks.

**Comment by dmachi** [comment] 2016-10-27 15:53
solr doesn’t have a GTE or LTE, thats why it isn’t implemented in the API.

**Comment by dmachi** [comment] 2016-10-27 15:54
Or maybe its visa versa (has GTE, but not GT), i can’t remember.

**Comment by chmao1** [comment] 2016-10-31 20:04
Fixed and will be included in the next build.

**Comment by mshukla1** [comment] 2016-11-15 09:20
Fixed. Verified on alpha.

**Closed by mshukla1** 2016-11-15 09:20 UTC
Labels: bug, fixed, Website / UI
