### ISSUE TITLE
Gene list doesn't finish loading.

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#116] opened 2015-03-25 14:53 UTC
From the results of the differential expression service, there is an option to get a gene list. When selected, the page never finishes loading, remaining in a spinning wheel state.

![screen shot 2015-03-25 at 10 52 23 am](https://cloud.githubusercontent.com/assets/991769/6827321/32a85af2-d2dd-11e4-8b58-208392fa1173.png)

**Comment by dmachi** [comment] 2015-03-25 15:09
Duplicate of #112

**Closed by dmachi** 2015-03-25 15:09 UTC
