### ISSUE TITLE
Production data API has hard limit of 250 records returned on all queries

### ISSUE THREAD

**Issue by cshenry** [PATRIC3/patric3_website#254] opened 2015-06-08 15:32 UTC
Production data API has hard limit of 250 records returned on all queries. Ideally this needs to be boosted over 10000.

**Comment by mshukla1** [comment] 2015-06-09 16:17
Dustin, please close the tickets, if the issue is resolved.

**Comment by dmachi** [comment] 2015-06-09 16:32
Resolved in beta. 25k limit, 25 default limit.

**Closed by dmachi** 2015-06-09 16:32 UTC
