### ISSUE TITLE
How many files are in this workspace directory?

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1625] opened 2017-08-08 13:50 UTC
![image](https://user-images.githubusercontent.com/7661533/29074964-a625e5a0-7c16-11e7-999b-54aa703f77e2.png)

**Comment by nconrad** [comment] 2018-07-17 18:25
Duplicate of https://github.com/PATRIC3/patric3_website/issues/1839.  But, note that you can get the count by selecting everything in the workspace (shift-click):

![image](https://user-images.githubusercontent.com/1194246/42837851-d90a1538-89c4-11e8-86a6-962d18353cd4.png)

**Closed as completed by nconrad** 2018-07-17 18:25 UTC
Labels: Enhancement, UI: Workspace

**Comment by rkenyon** [comment] 2018-08-03 20:45
Also related to #1627
