### ISSUE TITLE
Variation genome selector doesn't work with genome ID

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#648] opened 2016-03-30 17:48 UTC
I can't seem to type a genome ID into the genome selector

![image](https://cloud.githubusercontent.com/assets/2152226/14151869/aeedcfcc-f675-11e5-960b-285ded037b31.png)

**Comment by dawenx** [comment] 2017-09-14 20:11
This was reported more than 1 year ago and the problem was related to genome name selector. But I could not reproduce it from the production site today (09/14/2017). I would assume it was fixed as we improved genome name selector over the time. i suggest to close this issue (in a week) unless I hear objection from someone.

**Comment by mshukla1** [comment] 2017-09-17 17:07
Seems to be working now. Closing the ticket. 

<img width="385" alt="screen shot 2017-09-17 at 12 06 45 pm" src="https://user-images.githubusercontent.com/1236463/30523099-c5ad69c6-9ba0-11e7-9f54-74c3a9cf3333.png">

**Closed by mshukla1** 2017-09-17 17:07 UTC
Labels: Fixed, Service: Variation, Unable to Reproduce
