### ISSUE TITLE
MSA tool doesn't work

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1288] opened 2016-11-18 21:21 UTC
I've been waiting several minutes on an alignment of 2 proteins.

![image](https://cloud.githubusercontent.com/assets/7661533/20447111/bc0dfc60-ada2-11e6-82f7-0a695a6223e5.png)

**Comment by rkenyon** [comment] 2016-11-18 21:36
I just tried it with 6 features and it seemed to work.  Maybe something temporary with the website?

https://www.beta.patricbrc.org/view/MSA/?in(feature_id,(PATRIC.208435.3.NC_004116.CDS.54.1463.fwd,PATRIC.208435.3.NC_004116.CDS.1618.2754.fwd,PATRIC.208435.3.NC_004116.CDS.2824.3705.fwd,PATRIC.208435.3.NC_004116.CDS.3715.3912.fwd,PATRIC.208435.3.NC_004116.CDS.4150.4317.fwd,PATRIC.208435.3.NC_004116.CDS.4477.5592.fwd))

![screen shot 2016-11-18 at 4 34 45 pm](https://cloud.githubusercontent.com/assets/3188570/20447486/173e6804-adad-11e6-934c-d9e8a76419d9.png)

**Comment by jimdavis1** [comment] 2016-11-18 22:01
It's still not working. My proteins are from private genomes.  Maybe that's the reason? I've tried in safari and firefox.

![image](https://cloud.githubusercontent.com/assets/7661533/20448131/1946e3f6-ada8-11e6-92d5-f38cad3cdec9.png)

**Comment by aswarren** [comment] 2017-01-19 21:02
@jimdavis1 Try it again. Should be fixed now.

**Comment by hyoo** [comment] 2017-04-18 15:24
@jimdavis1 would you double check whether this works for you?

**Comment by hyoo** [comment] 2017-06-01 15:04
closing since i cannot reproduce the problem and had no other response.

**Closed as completed by hyoo** 2017-06-01 15:04 UTC
Labels: Fixed
