### ISSUE TITLE
Pathway heatmap-adding protein to group function just re write pop-up window

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1058] opened 2016-10-10 20:50 UTC
I selected a column of proteins from the heatmap viewer, then double clicked on Add Proteins to Group...it just redrew the pop-up box a little to the right of where it originally was.
<img width="640" alt="screen shot 2016-10-10 at 4 48 31 pm" src="https://cloud.githubusercontent.com/assets/11475316/19250675/a8a993da-8f09-11e6-8d4c-c9d248ed6e39.png">

**Comment by hyoo** [comment] 2016-10-10 20:54
#1031

**Comment by dmachi** [comment] 2016-10-11 19:36
Closing as duplicate of #1031

**Closed as completed by dmachi** 2016-10-11 19:36 UTC
