### ISSUE TITLE
Upload of adjusted file in differential expression app does not overwrite old data, and just hangs there

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#528] opened 2015-10-17 13:19 UTC
It took me a while to figure this out, and I don't know how often a user will encounter it, but I did so here goes.  Yesterday I uploaded a txt file into my workspace using the differential expression app.  The job failed, and I realized the file had some characters that the app didn't like (the gene ids had quotation marks around them).  After this was fixed, I tried to use the app again.  When I got to uploading the file, I clicked on it, then clicked upload file, and nothing happened.  It just hung there, doing nothing.  After about 5 minutes, I figured that it didn't like something, but there wasn't a message or anything.  I renamed the file, and then it worked.  Another user might not know to do this, and they might be stuck in upload limbo...there's a song in there somewhere...
![screen shot 2015-10-17 at 9 06 26 am](https://cloud.githubusercontent.com/assets/11475316/10558916/21c0d730-74b0-11e5-8b8a-eab876e43b2e.png)

**Comment by mshukla1** [comment] 2015-10-23 14:43
Andrew, I believe the problem is uploading multiple files with the same name. I am not sure if this is workspace UI or backend issue. Feel free to comment and reassign to someone else.

**Comment by aswarren** [comment] 2016-11-18 03:18
This was a temporary server issue.

**Closed by aswarren** 2016-11-18 03:18 UTC
Labels: Workspace
