### ISSUE TITLE
ID mapping popup list scrolled off screen

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#691] opened 2016-07-26 14:45 UTC
3.1.118alpha
![screen shot 2016-07-26 at 9 44 57 am](https://cloud.githubusercontent.com/assets/3188570/17142427/b62a3468-5315-11e6-980e-0bebd43e861e.png)

When clicking the ID Mapping action button, the popup box scrolls off the screen

**Comment by dmachi** [comment] 2016-08-02 20:05
Dupe of ticket closed yesterday.  I've taken steps to address this, though imperfectly.

**Closed by dmachi** 2016-08-02 20:05 UTC
