### ISSUE TITLE
BLAST result: select contigs and download FASTA has error

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1040] opened 2016-10-10 20:12 UTC
For the blast output to a contig, you should show the coordinates on the table view.  Ultimately, it would be nice to be able to select a row and download the fasta file of the region.  For now I just get the following error:

<img width="919" alt="screen shot 2016-10-10 at 3 12 05 pm" src="https://cloud.githubusercontent.com/assets/7661533/19249589/f1a0cb02-8efb-11e6-8f29-85c9920c811d.png">

**Comment by hyoo** [comment] 2016-10-12 20:44
I see this. Genome level FASTA download button is not working.

**Comment by hyoo** [comment] 2016-10-13 15:07
This is not working on other views as well. 

https://github.com/PATRIC3/patric3_website/issues/1078

**Comment by hyoo** [comment] 2016-10-13 15:20
Actually, this was due to #945. #1078 is a duplicate of #945. I have fixed and will be available soon.

**Closed as completed** 2016-10-18 02:27 UTC
Labels: Bug, Fixed
