### ISSUE TITLE
Selecting Pathway summary from the green bar in the Protein Family tab on private genome never loads

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1339] opened 2016-12-01 16:27 UTC
I waited a long time to get results after choosing a single protein family when looking at my private genome.  I was on the Protein Family tab, chose one PLFam, and selected the Pathway icon in the green bar.  Results never returned.

https://www.beta.patricbrc.org/view/PathwaySummary/?features=PATRIC.562.13094.562.13094.con.0006.CDS.103973.104392.fwd,PATRIC.562.13094.562.13094.con.0006.CDS.104441.106120.fwd

<img width="1426" alt="screen shot 2016-12-01 at 11 25 20 am" src="https://cloud.githubusercontent.com/assets/11475316/20802179/2cc371fe-b7b9-11e6-9654-52b7ba886941.png">

**Comment by hyoo** [comment] 2017-05-24 21:53
there was no mapping. It should cancel the spinning wheel. I will work on it.

**Comment by hyoo** [comment] 2017-05-24 22:02
hmm. I cannot reproduce it. 
https://www.patricbrc.org/view/PathwaySummary/?features=PATRIC.83332.12.NC_000962.CDS.9963.10160.fwd,PATRIC.83332.12.NC_000962.CDS.10484.10828.fwd,PATRIC.83332.12.NC_000962.CDS.10999.11121.fwd,PATRIC.83332.12.NC_000962.CDS.11555.11692.rev,PATRIC.83332.12.NC_000962.CDS.11874.12311.rev

It might be fixed, since this report was on 3.2.64 and we're currently 3.3.10. I am closing this ticket for now.

**Closed as completed by hyoo** 2017-05-24 22:02 UTC
