### ISSUE TITLE
DLP for Experiments: the link for "View All Experiment for This Genome" is incorrect

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#927] opened 2016-09-07 19:42 UTC
<img width="1253" alt="screen shot 2016-09-07 at 3 39 26 pm" src="https://cloud.githubusercontent.com/assets/6361802/18325937/901cb37c-7511-11e6-84a5-cdb21b9b486e.png">
<img width="843" alt="screen shot 2016-09-07 at 3 38 58 pm" src="https://cloud.githubusercontent.com/assets/6361802/18325941/93a28d32-7511-11e6-80da-7ba40a20b890.png">

**Comment by hyoo** [comment] 2016-09-07 21:55
I cannot reproduce it. please clean your cache and try again.

**Comment by maovt** [comment] 2016-09-08 15:05
Problem is that the link for "View All Experiment for This Genome" on the right panel is hard coded in DataType.js line 1090:

		_buildTranscriptomicsPopularPanel: function(){

			return [
				"<div class='genome-data right half'>",
					"<div id='dlp-transcriptomics-top-mutants'>",
						"<b>Top 5 Gene Modifications</b>",
					"</div>",
					"<div id='dlp-transcriptomics-top-conditions'>",
						"<b>Top 5 Experiment Conditions</b>",
					"</div>",
					"<p><a class='double-arrow-link' id='dlp-transcriptomics-linkout' href='ExperimentList?cType=genome&cId=83332.12&kw='>View All Experiment for This Genome</a></p>",
				"</div>"
			];
		},

**Comment by hyoo** [comment] 2016-09-08 19:47
thanks for clarification. now I understood the problem. I will fix it soon.

**Comment by hyoo** [comment] 2016-09-08 20:17
now fixed and available on alpha.

**Comment by mshukla1** [comment] 2016-10-11 20:13
fixed on beta.

**Closed by mshukla1** 2016-10-11 20:13 UTC
Labels: fixed
