### ISSUE TITLE
Feature group list in Proteome Comparison-reference option not alphabetical, or in order of most recent

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1346] opened 2016-12-02 12:36 UTC
When you have a lot of feature groups, this makes it difficult to step through.
<img width="593" alt="screen shot 2016-12-02 at 7 35 27 am" src="https://cloud.githubusercontent.com/assets/11475316/20834206/0ce66f7c-b862-11e6-8603-195e9332c447.png">

**Comment by mshukla1** [comment] 2016-12-02 13:34
this seems duplicate of #1347 . Closing this and leaving the other open.

**Closed as completed by mshukla1** 2016-12-02 13:34 UTC
