### ISSUE TITLE
Links to Genome, CDS and Browser on jobs page are broken

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2152] opened 2018-11-19 15:59 UTC

**Comment by ARWattam** [comment] 2018-11-19 16:00
You click on the 3 links at the top right of the page (before the green board) and nothing works.

**Comment by ARWattam** [comment] 2018-11-19 16:00
We have a webinar on genome annotation tomorrow (11/20).  It would be swell if this worked.

**Comment by nconrad** [comment] 2018-11-19 16:34
@olsonanl i'm looking at Rebecca's latest annotation run (job id: `f9b254c1-1972-454e-b277-17ea0a654890`) and it looks like the usual `autometa` from this run is missing.  Any idea why?
```
"{
    "id": "9DDE1AD2-EC10-11E8-B24C-E6B0682E0674",
    "path": "/ARWattam@patricbrc.org/home/Test folder/.Klebsiella pneumoniae 704SK6_complete/Klebsiella pneumoniae 704SK6_complete.genome",
    "name": "Klebsiella pneumoniae 704SK6_complete.genome",
    "type": "genome",
    "creation_time": "2018-11-19T15:34:34Z",
    "link_reference": "https://p3.theseed.org/services/shock_api/node/1724ce9e-2989-4088-a443-c60977dbfc8a",
    "owner_id": "ARWattam@patricbrc.org",
    "size": 21066834,
    "userMeta": {},
    "autoMeta": {
        "inspection_started": "2018-11-19T15:36:18Z",
        "is_folder": 0
    },
    "user_permission": "o",
    "global_permission": "n",
    "timestamp": 1542641674000
}"
```

Earlier run:
```
"{
    "id": "6A55A50A-E5CA-11E8-9514-9CF5682E0674",
    "path": "/ARWattam@patricbrc.org/home/Test folder/.Bacteria saeb test 4/.annotation/annotation.genome",
    "name": "annotation.genome",
    "type": "genome",
    "creation_time": "2018-11-11T15:56:56Z",
    "link_reference": "https://p3.theseed.org/services/shock_api/node/a0277e42-fb46-4ee0-859e-c0ae3a0e987f",
    "owner_id": "ARWattam@patricbrc.org",
    "size": 22468022,
    "userMeta": {},
    "autoMeta": {
        "N90": 32141,
        "is_folder": 0,
        "gc_content": 30.3036670091033,
        "taxonomy": null,
        "dna_size": 7353834,
        "ncbi_taxonomy_id": "2",
        "num_features": 7297,
        "scientific_name": "Bacteria saeb test 4",
        "domain": "Bacteria",
        "N50": 100514,
        "N70": 60789,
        "genome_id": "2.1969",
        "num_contigs": 174
    },
    "user_permission": "o",
    "global_permission": "n",
    "timestamp": 1541951816000
}"
```

**Comment by olsonanl** [comment] 2018-11-19 16:37
I will check; I updated workspace code and the autometa stuff there is delicate.


--bob


________________________________

**Comment by nconrad** [comment] 2018-11-19 16:40
hmmm... I also see the latest one there is `.Klebsiella pneumoniae 704SK6_complete/Klebsiella pneumoniae 704SK6_complete.genome` while the previous is `.annotation/annotation.genome`.    I'm just looking at what the UI is filtering out and using for the id:

https://github.com/PATRIC3/p3_web/blob/d6567eabfff24399ff82f12ce358bda5ce1455c8/public/js/p3/widget/viewer/GenomeAnnotation.js#L8-L20

**Comment by olsonanl** [comment] 2018-11-19 17:03
the autometa script was invoked:

```
Invoke /disks/p3/deployment/services/Workspace/bin/ws-autometa-job_result on /disks/p3/workspace/wsjobs/avz1JCHGMn/object.txt for ARWattam@patricbrc.org/home/Test folder/Klebsiella pneumoniae 704SK6_complete
```

Errors are logged, and there wasn't anything in the log.

I just instrumented the metadata scripts and it is being generated, and the genome link works properly.

It's not clear what is going on .

**Comment by olsonanl** [comment] 2018-11-19 17:09
The problem is that mongo is dumb. You can't have dots in keys in metadata. We were using contig ids for metadata keys (what a radical concept) and they break the mongo insert.

I've hacked the problem for now by not saving that bit of metadata

**Comment by nconrad** [comment] 2018-11-19 17:27
Fixed.  closing

**Closed as completed by nconrad** 2018-11-19 17:27 UTC
