### ISSUE TITLE
Genome table shows no contigs when there are actually many

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1848] opened 2018-01-17 22:44 UTC
All Bacteria genome table and sort on Sequences.  You will see that a number of them have no number listed.  Those genomes DO have contigs.  For example, 1450518.4 (genome ID) has 399 contigs.  There are 5 genomes that have this problem.
<img width="1430" alt="screen shot 2018-01-17 at 2 32 18 pm" src="https://user-images.githubusercontent.com/11475316/35071233-ddad99c0-fb94-11e7-8e2b-fbeeea0b780c.png">

**Comment by JoshuaVSherman** [comment] 2018-01-22 19:28
Discussed with Dustin and agree that this should be fixed in the data itself, where number of sequences is missing in the data

**Comment by rkenyon** [comment] 2018-08-16 16:01
I can't reproduce this problem.  @ARWattam please check.  The column is now named Contigs instead of Sequences, and when I sort on it using all bacteria, the smallest number I get is 1
![screen shot 2018-08-16 at 12 03 02 pm](https://user-images.githubusercontent.com/3188570/44220345-5cb8c700-a14c-11e8-9352-0a43d0efde91.png)

**Comment by ARWattam** [comment] 2018-09-11 19:47
I don't even see sequences as an option anymore, but contigs is most definitely working!  Another excellent job and this ticket can be closed!

**Comment by mshukla1** [comment] 2019-02-04 16:20
By popular demand and to avoid confusion, we have deprecated "sequences" field. Now, contigs represent total number of sequences, including chromosomes and plasmids. 

I have verified that the number of contigs are present for all genomes. 

-Maulik

**Closed as completed by mshukla1** 2019-02-04 16:20 UTC
Labels: High Priority
