### ISSUE TITLE
bug: de-selection after select all 

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1731] opened 2017-09-23 13:47 UTC
I was trying to create a genome group of B abortus genomes with less than 100 contigs.  When I loaded the entire taxon, went to the genome page, sorted on sequences, selected all, and then de-selected all genomes with less than 100 contigs, I got this error message:
dojo.js.uncompressed.js:324 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
s.getText @ dojo.js.uncompressed.js:324
www.patricbrc.org/:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at eval (/js/3.4.9/p3/layer/core.js:95:278)
p3.theseed.org/services/app_service Failed to load resource: the server responded with a status of 500 (Internal Server Error)
21p3.theseed.org/services/Workspace Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/js/3.4.9/p3/layer/core.js:966 Uncaught TypeError: Cannot use 'in' operator to search for 'genome_id' in undefined
    at Object.eval (/js/3.4.9/p3/layer/core.js:966:485)
    at https://www.patricbrc.org/js/3.4.9/dojo/dojo.js:58:501
    at Array.filter (<anonymous>)
    at Object.onCopy (/js/3.4.9/p3/layer/core.js:966:434)
    at Object.<anonymous> (https://www.patricbrc.org/js/3.4.9/dojo/dojo.js:58:446)
    at Object.<anonymous> (https://www.patricbrc.org/js/3.4.9/dojo/dojo.js:58:501)
    at Object.f [as onClick] (https://www.patricbrc.org/js/3.4.9/dojo/dojo.js:97:121)
    at Object._onClick (/js/3.4.9/p3/layer/core.js:297:319)
    at HTMLInputElement.<anonymous> (https://www.patricbrc.org/js/3.4.9/dojo/dojo.js:58:446)
    at Object.__onClick (/js/3.4.9/p3/layer/core.js:297:203)
/js/3.4.9/p3/layer/core.js:966 Uncaught TypeError: Cannot use 'in' operator to search for 'genome_id' in undefined
    at Object.eval (/js/3.4.9/p3/layer/core.js:966:485)
    at https://www.patricbrc.org/js/3.4.9/dojo/dojo.js:58:501
    at Array.filter (<anonymous>)
    at Object.onCopy (/js/3.4.9/p3/layer/core.js:966:434)
    at Object.<anonymous> (https://www.patricbrc.org/js/3.4.9/dojo/dojo.js:58:446)
    at Object.<anonymous> (https://www.patricbrc.org/js/3.4.9/dojo/dojo.js:58:501)
    at Object.f [as onClick] (https://www.patricbrc.org/js/3.4.9/dojo/dojo.js:97:121)
    at Object._onClick (/js/3.4.9/p3/layer/core.js:297:319)
    at HTMLInputElement.<anonymous> (https://www.patricbrc.org/js/3.4.9/dojo/dojo.js:58:446)
    at Object.__onClick (/js/3.4.9/p3/layer/core.js:297:203)
/js/3.4.9/p3/layer/core.js:966 Uncaught TypeError: Cannot use 'in' operator to search for 'genome_id' in undefined
    at Object.eval (/js/3.4.9/p3/layer/core.js:966:485)
    at https://www.patricbrc.org/js/3.4.9/dojo/dojo.js:58:501
    at Array.filter (<anonymous>)
    at Object.onCopy (/js/3.4.9/p3/layer/core.js:966:434)
    at Object.<anonymous> (https://www.patricbrc.org/js/3.4.9/dojo/dojo.js:58:446)
    at Object.<anonymous> (https://www.patricbrc.org/js/3.4.9/dojo/dojo.js:58:501)
    at Object.f [as onClick] (https://www.patricbrc.org/js/3.4.9/dojo/dojo.js:97:121)
    at Object._onClick (/js/3.4.9/p3/layer/core.js:297:319)
    at HTMLInputElement.<anonymous> (https://www.patricbrc.org/js/3.4.9/dojo/dojo.js:58:446)
    at Object.__onClick (/js/3.4.9/p3/layer/core.js:297:203)

However, I was able to create a group with ALL the genomes, then open the genome group and remove the genomes with more than 100 contigs.  There seems to be a problem in de-selecting from the original page

**Comment by mshukla1** [comment] 2017-09-26 02:57
@dawenx Not sure who exactly own this. Please take a look at the issue and feel free to reassign.

**Comment by dawenx** [comment] 2017-09-26 13:21
this probably relates to select all functionally as i see "undefined" in the error. when i tried to reproduce it, i also saw another error reported here, i.e., "https://p3.theseed.org/services/Workspace 500 (Internal Server Error)", this happened when i was typing group name in creating a new group. @nconrad can you check out this part? see the screen shot.
![issue_1731](https://user-images.githubusercontent.com/26723038/30862443-1137c182-a29c-11e7-86a8-980479a22480.png)

**Comment by nconrad** [comment] 2017-09-26 16:03
I didn't write this bit, but yeah, it looks like it's related to the select all button, not the errors.

Those other errors are because the only way to check for an existing file is to call the `workspace.get` (metadataonly=true) api method, and that will return a 500 server error if the file doesn't exist.  It is being called to make sure the group name doesn't already exist.

![image](https://user-images.githubusercontent.com/1194246/30870574-d227be12-a2a9-11e7-8cd1-df267283a2f0.png)

**Comment by dawenx** [comment] 2017-09-26 16:10
thanks @nconrad good to know 500 server error is benign. i will try to work on the select all bug then.

**Comment by dawenx** [comment] 2017-09-26 17:15
this is a site wide issue and it's similar to issue #1717. i'm testing my fix on my local, will submit a PR when i'm ready. @hyoo

**Comment by dawenx** [comment] 2017-09-26 17:50
i think i have fixed this issue and made it general to support other tabs. PR submitted.

**Comment by nconrad** [comment] 2017-09-26 18:28
great!

**Comment by ARWattam** [comment] 2017-09-26 18:53
Is it on production?

Rebecca

**Comment by hyoo** [comment] 2017-09-26 19:38
on alpha.

**Comment by dawenx** [comment] 2017-10-02 14:09
@ARWattam FYI, this is on production now.

**Closed as completed by dawenx** 2017-10-02 14:09 UTC
Labels: Fixed, UI
