### ISSUE TITLE
RNA-seq: no differential expression output 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1998] opened 2018-05-24 20:44 UTC
yesterday, I ran a differential expression job on behalf of a user. The job completed successfully. 

I see differential expression job result object in the output folder. However, when I click on it, it doesn;t have any result files and I can't load gene list or experiment details. 

The differential expression job parameters show the following. Note that the job output path is set to scratch space and not the workspace directory. 

This is critical bug and needs to be fixed asap. 

-Maulik

{   "experiment_title": "RNA-Seq",   "xsetup": "gene_matrix",   "xformat": "tsv",   "xfile": "/scratch/tmp/CZzkZWf9Ty/Rocket/226186.12/gene_exp.gmx",   "experiment_description": "RNA-Seq",   "data_type": "Transcriptomics",   "output_path": "/scratch/tmp/CZzkZWf9Ty/Rocket/.RNAseq_test3_diffexp",   "source_id_type": "patric_id",   "organism": "226186.12" }
--

<img width="1076" alt="screen shot 2018-05-24 at 3 43 05 pm" src="https://user-images.githubusercontent.com/1236463/40512680-30b1ac1e-5f69-11e8-8864-dab95e0e55c2.png">

**Comment by olsonanl** [comment] 2018-05-29 20:19
This has become a problem for Rebecca with the ASM workshop prep.

@aswarren what needs to be done if I understand this right is that the generated job result file cannot refer to local path names (as we discussed earlier); any filename there needs to be a workspace path that corresponds to the location in the workspace where the files were copied (via the mechanism in the app script of the ```@outputs``` list.

The fix for this will involve both the prok_tuxedo code (which actually should not be the entity writing the file since it does not have all of proper information at hand) and the App-RNASeq.pl code.

**Comment by aswarren** [comment] 2018-05-31 20:11
@olsonanl I am 99% sure that isn't the problem. We fixed most of the bugs with respect to the job object having actual paths because they need to be capable of being moved. So we no longer depend on those paths in any way.

The problem is, for some reason, the differential expression folder is empty of JSON files:
![image](https://user-images.githubusercontent.com/229173/40805684-0a7217bc-64ed-11e8-8972-5d37939887a1.png)

It is strange because I can successfully run the diffexp import command listed in the StdErr/Out from her job.
./expression_transform.py --ufile /scratch/tmp/EQ4EmKNduE/Rocket/1310581.3/diff_exp_params.json --sstring '{"data_api":"http://chestnut.mcs.anl.gov:3001/genome_feature"}' --output_path ./A test --xfile /scratch/tmp/EQ4EmKNduE/Rocket/1310581.3/gene_exp.gmx

Though for running from the command line I did put single quotes around the JSON string and got rid of spaces in the output path which weren't escaped.

**Comment by aswarren** [comment] 2018-05-31 20:44
@olsonanl So it looks like the output is created successfully as well from the expression_transform.py
```
[anwarren@redwood .A_baumannii 34654 AMR Tuxedo_diffexp]$ pwd
/scratch/tmp/EQ4EmKNduE/Rocket/.A_baumannii 34654 AMR Tuxedo_diffexp
[anwarren@redwood .A_baumannii 34654 AMR Tuxedo_diffexp]$ ls -lh
total 1.8M
-rw-r--r--. 1 iris iris  238 May 30 14:42 experiment.json
-rw-r--r--. 1 iris iris 1.6M May 30 14:42 expression.json
-rw-r--r--. 1 iris iris 252K May 30 14:42 mapping.json
-rw-r--r--. 1 iris iris  720 May 30 14:42 sample.json
```
It's just not getting copied over into the output.

**Comment by aswarren** [comment] 2018-05-31 20:53
@olsonanl I think that this line puts the folder in the output

https://github.com/olsonanl/app_service/blob/master/scripts/App-RNASeq.pl#L243

And that here we create that folder?

https://github.com/olsonanl/app_service/blob/master/scripts/App-RNASeq.pl#L76-L87

But we never copy the contents of that folder into the new instance of the folder?

**Comment by olsonanl** [comment] 2018-05-31 20:55
Can you verify that the user of the data does not look at the data in the job result object? 

Regarding the copying; are the json files included in the file list? The copies made are not recursive. If you want them to be you'll need to code the recursive copy; just including a folder in the output list will not copy the contents.

**Comment by aswarren** [comment] 2018-05-31 21:43
@olsonanl I'm not sure what you mean by: "Can you verify that the user of the data does not look at the data in the job result object?"

I can verify that we are no longer using those paths anywhere through a list of commits from Neal and myself so that the job objects can be moved into new folders and still work correctly.

Wrt copying no, based on our previous discussions I was under the mistaken impression that the copies were recursive.

Do you think this will take care of it?
https://github.com/olsonanl/app_service/pull/43

**Comment by olsonanl** [comment] 2018-05-31 22:02
What I mean is that the job object has paths in it that are filesystem paths, not workspace paths. That was Maulik's original bug report. If the code that uses that job object expects to read the xfile and/or output_path values to pull files, it will fail. 

Regarding that PR, no, it has a problem that I've noted in the PR.

**Closed as completed** 2018-06-28 00:40 UTC
Labels: Bug, Critical, Service: RNA-seq
