### ISSUE TITLE
New home page: search bar disappears

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1988] opened 2018-05-14 15:18 UTC
If you go outside the new homepage anywhere, the search bar disappears.

![image](https://user-images.githubusercontent.com/1236463/40006500-2d1b2cda-5760-11e8-94e6-410e8986e3aa.png)

**Comment by chris-c-thomas** [comment] 2018-05-14 15:32
Duplicate of [Issue #1930](https://github.com/PATRIC3/patric3_website/issues/1930)

Fixed in [PR #743 to Develop](https://github.com/PATRIC3/p3_web/pull/743) - I don't think it's on production yet? @hyoo

**Comment by hyoo** [comment] 2018-05-15 20:13
this is deployed on alpha and fixed.

**Closed as completed by hyoo** 2018-05-15 20:13 UTC
