### ISSUE TITLE
Two download buttons in vertical green bar when looking at feature groups

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1865] opened 2018-01-27 15:56 UTC
Have two download icons right above each other, and one in blue above the table, is triply confusing.  See attached image
<img width="1138" alt="screen shot 2018-01-27 at 10 54 43 am" src="https://user-images.githubusercontent.com/11475316/35473596-b2807cd6-0350-11e8-9921-fb6026e3bdec.png">

**Comment by JoshuaVSherman** [comment] 2018-01-29 13:08
@ARWattam need help to reproduce this please
![image](https://user-images.githubusercontent.com/13340120/35511859-9e45a616-04cb-11e8-9c59-53920846b8c0.png)

**Comment by nconrad** [comment] 2018-01-29 16:40
This a duplicate of #1635 .  I'm assuming nobody is using the button that downloads JSON, so I'm going to remove it.

**Closed as completed** 2018-01-29 16:40 UTC

**Comment by nconrad** [comment] 2018-01-29 17:10
oh, btw, @JoshuaVSherman, to replicate, the objects have to be of type `feature_group`, `genome_group`, etc., and you also can only download one item at a time.
