### ISSUE TITLE
Genomic Features from menu bar

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#701] opened 2016-07-26 14:52 UTC
Blank page

<img width="540" alt="screen shot 2016-07-26 at 9 52 01 am" src="https://cloud.githubusercontent.com/assets/8005288/17142708/b9f0822c-5316-11e6-9e3a-c9289438d80b.png">

**Comment by dmachi** [comment] 2016-07-27 03:27
Duplicate of #705

**Closed by dmachi** 2016-07-27 03:27 UTC
