### ISSUE TITLE
blast

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1915] opened 2018-03-15 11:40 UTC
I blasted this PATRIC protein against all Klebsiella.  It did not find itself.

>fig|573.12458.peg.5560|B8O09_27400|   Class D beta-lactamase (EC 3.5.2.6) => OXA-1 family   [Klebsiella pneumoniae strain KPN1482 | 573.12458]
MKNTIHINFAIFLIIANIIYSSASASTDISTVASPLFEGTEGCFLLYDASTNAEIAQFNK
AKCATQMAPDSTFKIALSLMAFDAEIIDQKTIFKWDKTPKGMEIWNSNHTPKTWMQFSVV
WVSQEITQKIGLNKIKNYLKDFDYGNQDFSGDKERNNGLTEAWLESSLKISPEEQIQFLR
KIINHNLPVKNSAIENTIENMYLQDLDNSTKLYGKTGAGFTANRTLQNGWFEGFIISKSG
HKYVFVSALTGNLGSNLTSSIKAKKNAITILNTLNL

![image](https://user-images.githubusercontent.com/7661533/37461283-d35a87e0-281b-11e8-92fe-b8a8e69f7ed3.png)

![image](https://user-images.githubusercontent.com/7661533/37461151-79edfd22-281b-11e8-9c74-ff836b50fdd7.png)

Actually it misses at least 3 other Kleb genomes that are in PATRIC.  This is from a blast of a genome group.

![image](https://user-images.githubusercontent.com/7661533/37461410-468b81e2-281c-11e8-9728-5f390f8a59aa.png)

**Comment by rkenyon** [comment] 2018-08-03 20:00
Jim triage comment: Medium.  If we are serious about supporting AMR research, then this should be done.   Oddly, Jim was the person that closed this issue.

**Comment by hyoo** [comment] 2019-01-25 16:47
This is a duplicate of #1916

**Closed as completed by hyoo** 2019-01-25 16:47 UTC
Labels: Review, Service: BLAST
