### ISSUE TITLE
duplicate folders in workspace

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#836] opened 2016-08-12 21:04 UTC
These two folders in my workspace appear to be the same, and appear to have the same contents.

![image](https://cloud.githubusercontent.com/assets/991769/17636998/51b4b032-60a6-11e6-81cb-7cca8b2f4556.png)

**Comment by hyoo** [comment] 2017-05-11 19:53
@nconrad would you check whether we still have this issue or not?

**Comment by nconrad** [comment] 2017-07-27 19:11
I haven't seen this issue with encoded spaces yet, but we have seen duplicate folders/object issues before.  I'll close this ticket because the issue is referenced here: https://github.com/PATRIC3/Workspace/issues/22

**Closed** 2017-07-27 19:11 UTC
