### ISSUE TITLE
Hard to add a column in table

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#982] opened 2016-10-05 21:43 UTC
Maybe this is a problem.  You can see that I added Length (AA):
<img width="1131" alt="screen shot 2016-10-05 at 5 40 56 pm" src="https://cloud.githubusercontent.com/assets/11475316/19132752/1c4d4e8e-8b23-11e6-882d-2a0d59d395d7.png">

But it never showed up in the table, or across the top to show me that it had been added:
<img width="1163" alt="screen shot 2016-10-05 at 5 41 11 pm" src="https://cloud.githubusercontent.com/assets/11475316/19132776/2f05dac8-8b23-11e6-814f-a4526f351b85.png">

**Comment by dmachi** [comment] 2016-10-06 01:09
Duplicate of #979

**Closed as completed by dmachi** 2016-10-06 01:09 UTC
