### ISSUE TITLE
Expression condition selection on an RNA seq job result page does not work on firefox.

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#305] opened 2015-06-16 16:35 UTC
@janakagithub reports this

![image](https://cloud.githubusercontent.com/assets/1194246/8188480/e43e6ee4-141b-11e5-9cd8-b65483495a2e.png)

**Comment by olsonanl** [comment] 2015-08-05 20:34
Verified. You can see this in the workshopdemo dataset workshopdemo / home / Experiments / Antibiotic resistance in baumannii 

Here is the javascript output on safari. 

```
[Log] Filtering f:  ["/workshopdemo@patricbrc.org/home/Experiments/.Antibiotic resistance in baumannii/experiment.json", "C8AAA9A8-2A4C-11E5-A7B0-E2C2682E0674"]
[Log] Filtering f:  ["/workshopdemo@patricbrc.org/home/Experiments/.Antibiotic resistance in baumannii/expression.json", "C8B616EE-2A4C-11E5-83EE-5FC4682E0674"]
[Log] Filtering f:  ["/workshopdemo@patricbrc.org/home/Experiments/.Antibiotic resistance in baumannii/sample.json", "C95D2394-2A4C-11E5-9DAB-01C4682E0674"]
[Log] Filtering f:  ["/workshopdemo@patricbrc.org/home/Experiments/.Antibiotic resistance in baumannii/mapping.json", "C90E4FA8-2A4C-11E5-8568-5FC4682E0674"]
[Log] Experiment Sub Paths:  ["/workshopdemo@patricbrc.org/home/Experiments/.Antibiotic resistance in baumannii/experiment.json", "/workshopdemo@patricbrc.org/home/Experiments/.Antibiotic resistance in baumannii/sample.json"]
[Log] Got sample Data:  
Object

[Log] results:  [
Object
, 
Object
, 
Object
]
[Log] Total Rows:  3
[Log] dgrid-select:  
Event
bubbles: true
cancelBubble: false
cancelable: false
clipboardData: undefined
currentTarget: null
defaultPrevented: false
eventPhase: 0
grid: Object
parentType: "mousedown"
returnValue: true
rows: Array[1]
srcElement: div.dgrid-content ui-widget-content
target: div.dgrid-content ui-widget-content
timeStamp: 1438806810933
type: "dgrid-select"
__proto__: EventPrototype
```

**Comment by olsonanl** [comment] 2015-08-05 20:35
here is the javascript output on firefox, with the error.

```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ dojo.js:19:0
"Filtering f: " Array [ "/workshopdemo@patricbrc.org/home/Ex…", "C8AAA9A8-2A4C-11E5-A7B0-E2C2682E0674" ] Experiment.js:19:5
"Filtering f: " Array [ "/workshopdemo@patricbrc.org/home/Ex…", "C8B616EE-2A4C-11E5-83EE-5FC4682E0674" ] Experiment.js:19:5
"Filtering f: " Array [ "/workshopdemo@patricbrc.org/home/Ex…", "C95D2394-2A4C-11E5-9DAB-01C4682E0674" ] Experiment.js:19:5
"Filtering f: " Array [ "/workshopdemo@patricbrc.org/home/Ex…", "C90E4FA8-2A4C-11E5-8568-5FC4682E0674" ] Experiment.js:19:5
"Experiment Sub Paths: " Array [ "/workshopdemo@patricbrc.org/home/Ex…", "/workshopdemo@patricbrc.org/home/Ex…" ] Experiment.js:40:4
"Got sample Data: " Object { metadata: Object, data: Object } Experiment.js:51:5
"results: " Array [ Object, Object, Object ] Grid.js:71:5
"Total Rows: " 3 Grid.js:55:4
"dgrid-select: " dgrid-select { target: <div.dgrid-content.ui-widget-content>, isTrusted: false, currentTarget: <div#dgrid_0.dgrid.dgrid-grid.ui-widget.ExperimentViewer-child.ExperimentViewerPane.dijitAlignCenter>, eventPhase: 3, bubbles: true, cancelable: false, defaultPrevented: false, timeStamp: 1438806785167446, originalTarget: <div.dgrid-content.ui-widget-content>, explicitOriginalTarget: #text "COL|MERO", NONE: 0 } Experiment.js:100:41
ReferenceError: event is not defined dojo.js line 19 > Function line 1 > eval:102:48
Use of getAttributeNode() is deprecated. Use getAttribute() instead.
```

**Comment by aswarren** [comment] 2015-08-24 21:40
Dustin found the evt emit problem. Assigning to him for label fixing

**Comment by dmachi** [comment] 2015-08-26 18:53
I'm having trouble reproducing this since the event error has been fixed. I see the icon for "genes" show up (with label) as well as the content in the item detail panel.  Am I missing something?

![mozilla firefox](https://cloud.githubusercontent.com/assets/190574/9502927/04ebdf78-4c02-11e5-8827-4d187b46de25.png)

**Comment by mshukla1** [comment] 2015-10-30 16:20
Verified that
- when a single condition is selected, metadata is displayed in the right panel
- when multiple conditions are selected, number  selected is shown
- for any selection icon for gene table is displayed

closing the ticket.

**Closed by mshukla1** 2015-10-30 16:20 UTC
Labels: Services
