### ISSUE TITLE
Need checkboxes for the feature transcriptomics table

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#831] opened 2016-08-12 15:10 UTC
For example: the table for
https://www.alpha.patricbrc.org/view/Feature/PATRIC.186103.3.NC_003485.CDS.1041280.1041501.rev#view_tab=transcriptomics

**Comment by hyoo** [comment] 2016-08-12 19:17
#700

**Comment by dmachi** [comment] 2016-10-06 18:14
Duplicate of #700

**Closed** 2016-10-06 18:14 UTC
