### ISSUE TITLE
Discrepancy between job progress and completion

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1333] opened 2016-12-01 13:58 UTC
I went to the annotation app and started 4 annotation jobs from assemblies that I started yesterday and apparently completed overnight...I could see the contigs available for annotation.  After submitting the 4 jobs, I went to the Jobs page to see the progress....just to be clear, from the annotation submission page I clicked on Jobs at the bottom of that page and overwrote it.  I was surprised to see that the Assembly jobs were still listed as in progress...the same assemblies I had just submitted for annotation.  There seems to be a lag in reporting the progress I guess.
<img width="1101" alt="screen shot 2016-12-01 at 8 55 25 am" src="https://cloud.githubusercontent.com/assets/11475316/20796490/5e3d4260-b7a4-11e6-9c68-ec26c1329059.png">

**Comment by dmachi** [comment] 2016-12-01 16:02
Duplicate of #1170

**Closed as completed by dmachi** 2016-12-01 16:02 UTC
