### ISSUE TITLE
Vertical scroll bar on pathway map isn't working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1102] opened 2016-10-16 19:51 UTC
I couldn't get anywhere with it.
<img width="1436" alt="screen shot 2016-10-16 at 3 50 13 pm" src="https://cloud.githubusercontent.com/assets/11475316/19420374/5d87e650-93b8-11e6-9691-d7c9bead46c3.png">

**Comment by mshukla1** [comment] 2016-10-18 01:39
I was able to reproduce it and agree it is a major problem. 

-Maulik

**Comment by hyoo** [comment] 2016-10-18 10:15
I see this in the others heatmaps too. Quick work around is, resize a little bit, and then it will work.
I will take a look, but I may not be able to fix it before the workshop.

**Comment by hyoo** [comment] 2016-11-16 17:36
anyone has any idea?

**Comment by hyoo** [comment] 2016-11-21 22:33
I was suspecting a z-index but I cannot reproduce it. I want to verify the z-index will help or not.

**Comment by hyoo** [comment] 2016-11-30 16:15
please try again to see whether you can reproduce it or not. I could not reproduce it after applying this.

**Comment by rkenyon** [comment] 2016-12-01 22:34
Verified that it is working now.  Closing this ticket.

**Closed as completed by rkenyon** 2016-12-01 22:34 UTC
Labels: Bug, Fixed, Critical
