### ISSUE TITLE
Chrome bug in metagenome binning upload

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1831] opened 2017-12-19 20:21 UTC
To reproduce:

Select a set of contigs.
Click in the output folder text, and start typing a name that already exists. It will give an autofill suggestion from a dropdown. Hit return to accept the chosen path. 

This results in the chosen path being chosen, and it submits the job which will fail because it is incomplete. 

I couldn't replicate this in Safari but could in chrome. Here's an example:

https://youtu.be/-OjVNtuWtuU

**Comment by JoshuaVSherman** [comment] 2018-01-25 16:44
I was not able to reproduce this with my chrome

**Comment by nconrad** [comment] 2018-01-29 18:29
@dawenx offered to look into this.

**Comment by dawenx** [comment] 2018-02-06 14:06
this is fixed on alpha along with some other enhancements, e.g., a user cannot choose both paired read library and contigs, same file for a paired is not allowed, etc.

@olsonanl can you confirm the fix? thanks!

**Closed as completed** 2018-02-09 21:13 UTC
Labels: Fixed, UI, Service: Metagenome Binning
